"use client";

import { useState, useMemo, useRef } from "react";
import { useRouter } from "next/navigation";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faRobot,
  faPlus,
  faSearch,
  faTimes,
  faEye,
  faUserPlus,
  faListCheck,
  faHeartbeat,
  faStethoscope,
  faCalendarDay,
  faHospitalUser,
  faNotesMedical,
  faExclamationTriangle,
  faUsers,
  faUser,
  faChevronDown,
  faLayerGroup,
  faPenToSquare,
  faTrash,
  faTriangleExclamation,
  faFileImport,
  faCheck,
  faMinus,
  faClock,
} from "@fortawesome/free-solid-svg-icons";
import { toast } from "../../components/Toast";
import {
  fetchFacultyScenarios,
  createScenario,
  updateScenario,
  deleteScenario,
  generateScenarioBatch,
  ScenarioDraft,
  SimulationScenario,
  fetchFacultyStudents,
  FacultyStudent,
  assignScenarioToStudents,
  fetchFacultyTeams,
  logAuditAction,
  getCurrentFacultyUser,
  fetchFacultyPatients,
  assignPatientRooms,
  FacultyPatient,
} from "../../lib/api";
import { usePageData } from "../../lib/use-page-data";
import { SkeletonStatTile, SkeletonScenarioCard } from "../../components/skeletons";
import PageHeader from "../../components/PageHeader";
import StatTile from "../../components/StatTile";
import Card from "../../components/Card";
import Avatar from "../../components/Avatar";
import ActionsMenu from "../../components/ActionsMenu";
import { EcgLoader } from "../../components/EcgLoader";
import { LessonPanel, useLessonImport } from "../../components/LessonImport";
import {
  ChapterCard,
  PlanLegend,
  PlanStrip,
  RoomModeCard,
  Step,
  TAUGHT_CHAPTERS,
  chapterName,
  hueStyle,
} from "./library-plan";

const inputClassName =
  "w-full px-4 py-3 bg-surface border border-gray-400 rounded-xl text-gray-900 placeholder:text-gray-600 focus:outline-none focus:ring-2 focus:ring-brand-600/30 focus:border-brand-600 focus:bg-surface transition-all text-sm shadow-sm";

/** The batch route caps a single request at 12 (sequential, rate-limited AI
 *  generation, inside a 60s serverless timeout). Larger counts are generated by
 *  looping the route in sub-batches of this size — no fixed total ceiling. */
const MAX_PER_REQUEST = 12;

// Stable empty fallbacks, so the memos below them are not invalidated by a
// fresh `[]` on every render.
const NO_SCENARIOS: SimulationScenario[] = [];
const NO_STUDENTS: FacultyStudent[] = [];

const labelClassName = "block text-sm font-bold text-gray-800 mb-2";

export default function FacultyScenariosClient() {
  const router = useRouter();

  const [searchQuery, setSearchQuery] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("all");

  const [patients, setPatients] = useState<FacultyPatient[]>([]);
  const [loadingPatients, setLoadingPatients] = useState(false);

  const [showBatchModal, setShowBatchModal] = useState(false);
  // The committed numeric count that generation uses, plus the raw field text so
  // it can be cleared and retyped freely without snapping back mid-edit.
  const [batchCount, setBatchCount] = useState(6);
  const [batchCountInput, setBatchCountInput] = useState("6");
  const [batchChapters, setBatchChapters] = useState<number[]>([]);
  const [batchTopic, setBatchTopic] = useState("");
  // How the library's grounded patients are placed into rooms on save.
  const [batchRoomMode, setBatchRoomMode] = useState<"fill" | "spread">("fill");
  const [batchDrafts, setBatchDrafts] = useState<ScenarioDraft[] | null>(null);
  const [batchSelected, setBatchSelected] = useState<number[]>([]);
  const [batchGenerating, setBatchGenerating] = useState(false);
  const [batchProgress, setBatchProgress] = useState(0);
  const [batchCancelling, setBatchCancelling] = useState(false);
  // Refs, not state: the running generate loop reads these synchronously and a
  // state update wouldn't reach its closure in time to stop the next sub-batch.
  const batchCancelRef = useRef(false);
  const batchAbortRef = useRef<AbortController | null>(null);
  const [batchSaving, setBatchSaving] = useState(false);
  const [batchSavedCount, setBatchSavedCount] = useState(0);
  const [batchError, setBatchError] = useState<string | null>(null);
  const [batchWarning, setBatchWarning] = useState<string | null>(null);
  // A lesson grounds every scenario in the library, and its ticked topics
  // replace the category picker — one scenario per topic to start with.
  const batchLesson = useLessonImport({
    onAnalyzed: (imported) => {
      if (imported.topics.length > 0) {
        setBatchCount(imported.topics.length);
        setBatchCountInput(String(imported.topics.length));
      }
    },
  });
  const batchUsesTopics = (batchLesson.lesson?.topics.length ?? 0) > 0;
  // The chapter each planned case will be built around, in the order the
  // batch cycles through them (the server shuffles when none is picked).
  const planPool = batchUsesTopics
    ? batchLesson.selectedTopics.map((t) => t.chapter)
    : batchChapters.length > 0
      ? batchChapters
      : TAUGHT_CHAPTERS.map((c) => c.chapter);
  const planSequence = Array.from({ length: batchCount }, (_, i) =>
    planPool.length > 0 ? planPool[i % planPool.length] : undefined,
  );

  const [showDetailsModal, setShowDetailsModal] = useState(false);
  const [selectedScenario, setSelectedScenario] = useState<SimulationScenario | null>(null);

  const [showAssignModal, setShowAssignModal] = useState(false);

  const [selectedStudents, setSelectedStudents] = useState<string[]>([]);
  // Teams picked in the assign modal; each member is assigned on their own.
  const [assignHasTeams, setAssignHasTeams] = useState(false);
  const [assignDeadline, setAssignDeadline] = useState("");
  const [assignRequired, setAssignRequired] = useState(false);
  const [studentSearchQuery, setStudentSearchQuery] = useState("");
  const [assigning, setAssigning] = useState(false);

  const [showLinkPatientModal, setShowLinkPatientModal] = useState(false);
  const [linkPatientTarget, setLinkPatientTarget] = useState<SimulationScenario | null>(null);
  const [linkPatientId, setLinkPatientId] = useState("");
  const [linkPatientSearchQuery, setLinkPatientSearchQuery] = useState("");
  const [savingPatientLink, setSavingPatientLink] = useState(false);

  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<SimulationScenario | null>(null);
  const [deleting, setDeleting] = useState(false);
  const [deleteError, setDeleteError] = useState<string | null>(null);

  const { data, loading, refresh, setData } = usePageData("faculty:scenarios", async () => {
    const [scenarios, students] = await Promise.all([
      fetchFacultyScenarios(),
      fetchFacultyStudents(),
    ]);
    return { scenarios, students };
  });

  const scenarios = data?.scenarios ?? NO_SCENARIOS;
  const students = data?.students ?? NO_STUDENTS;
  const loadScenarios = refresh;

  const loadPatientsForSelector = async () => {
    setLoadingPatients(true);
    const data = await fetchFacultyPatients();
    setPatients(data);
    setLoadingPatients(false);
  };

  const categories = useMemo(
    () => Array.from(new Set(scenarios.map((s) => s.category).filter(Boolean))),
    [scenarios],
  );

  const filteredScenarios = useMemo(() => {
    return scenarios.filter((scenario) => {
      const matchesSearch =
        scenario.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        scenario.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
        scenario.category.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesCategory = categoryFilter === "all" || scenario.category === categoryFilter;
      return matchesSearch && matchesCategory;
    });
  }, [scenarios, searchQuery, categoryFilter]);

  const linkModalFilteredPatients = useMemo(() => {
    const q = linkPatientSearchQuery.toLowerCase();
    return patients.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        p.diagnosis.toLowerCase().includes(q) ||
        (p.mimic_id || "").toLowerCase().includes(q) ||
        p.room_number.toLowerCase().includes(q),
    );
  }, [patients, linkPatientSearchQuery]);

  const linkPatientSelected = useMemo(
    () => patients.find((p) => p.id === linkPatientId) || null,
    [patients, linkPatientId],
  );

  const openBatchModal = () => {
    setBatchDrafts(null);
    setBatchSelected([]);
    setBatchError(null);
    setBatchWarning(null);
    setBatchSavedCount(0);
    setBatchProgress(0);
    setBatchCancelling(false);
    batchLesson.remove();
    setShowBatchModal(true);
    if (patients.length === 0) void loadPatientsForSelector();
  };

  const closeBatchModal = () => {
    if (batchGenerating || batchSaving) return;
    setShowBatchModal(false);
    setBatchDrafts(null);
    setBatchSelected([]);
    setBatchError(null);
    setBatchWarning(null);
    setBatchSavedCount(0);
    setBatchProgress(0);
    setBatchCancelling(false);
  };

  const toggleBatchChapter = (chapter: number) => {
    setBatchChapters((prev) =>
      prev.includes(chapter) ? prev.filter((c) => c !== chapter) : [...prev, chapter],
    );
  };

  /** Stops the generate loop and aborts the request in flight, keeping whatever
   *  sub-batches already came back. */
  const cancelBatch = () => {
    batchCancelRef.current = true;
    batchAbortRef.current?.abort();
    setBatchCancelling(true);
  };

  const handleGenerateBatch = async () => {
    batchCancelRef.current = false;
    setBatchCancelling(false);
    setBatchGenerating(true);
    setBatchError(null);
    setBatchWarning(null);
    setBatchDrafts(null);
    setBatchProgress(0);

    // With a lesson, its ticked chapters replace the chapter picker.
    const chapters = batchUsesTopics
      ? batchLesson.selectedTopics.map((t) => t.chapter)
      : batchChapters;

    const total = Math.max(1, batchCount);
    const collected: ScenarioDraft[] = [];
    const warnings: string[] = [];

    // A single request tops out at the server's per-batch cap (60s serverless
    // limit), so a larger library is several sequential requests. Each carries
    // the titles produced so far as avoid_titles, so sub-batches don't collide.
    for (let remaining = total; remaining > 0; remaining -= MAX_PER_REQUEST) {
      if (batchCancelRef.current) break;
      const chunkCount = Math.min(MAX_PER_REQUEST, remaining);
      const controller = new AbortController();
      batchAbortRef.current = controller;
      const result = await generateScenarioBatch(
        {
          count: chunkCount,
          chapters,
          topic: batchTopic.trim() || undefined,
          lessonText: batchLesson.lesson?.lessonText,
          avoidTitles: collected.map((s) => s.title),
        },
        controller.signal,
      );

      // A cancel lands here as an aborted-fetch error; treat it as a clean stop.
      if (batchCancelRef.current) break;

      if ("error" in result) {
        // A first-request failure is fatal; a later one keeps what we have.
        if (collected.length === 0) {
          setBatchError(result.error);
          setBatchGenerating(false);
          return;
        }
        warnings.push(result.error);
        break;
      }

      collected.push(...result.scenarios);
      if (result.warning) warnings.push(result.warning);
      setBatchProgress(collected.length);

      // The model can return fewer than asked; stop rather than loop chasing the rest.
      if (result.scenarios.length < chunkCount) break;
    }

    batchAbortRef.current = null;
    const cancelled = batchCancelRef.current;
    setBatchCancelling(false);

    if (collected.length === 0) {
      // A cancel with nothing in hand just returns to the form, no error.
      if (!cancelled) {
        setBatchError("The AI service didn't return any patient cases. Please try again.");
      }
      setBatchGenerating(false);
      return;
    }

    setBatchDrafts(collected);
    setBatchSelected(collected.map((_, i) => i));
    setBatchWarning(
      cancelled
        ? `Stopped at ${collected.length} scenario${collected.length === 1 ? "" : "s"}. Keep these or generate more.`
        : collected.length < total
          ? `Generated ${collected.length} of ${total} — the AI service fell short. Keep these or try again for more.`
          : (warnings[0] ?? null),
    );
    setBatchGenerating(false);
  };

  const handleSaveBatch = async () => {
    if (!batchDrafts || batchSelected.length === 0) return;

    setBatchSaving(true);
    setBatchSavedCount(0);

    const chosen = batchSelected
      .slice()
      .sort((a, b) => a - b)
      .map((i) => batchDrafts[i]);

    let saved = 0;
    const savedPatientIds: string[] = [];
    for (const draft of chosen) {
      const created = await createScenario({
        title: draft.title,
        description: draft.description,
        category: draft.category,
        patient_case: draft.patient_case,
        patient_id: draft.patient_id,
        learning_objectives: draft.learning_objectives,
        is_ai_generated: true,
        skills: (draft.skills ?? []).map((id) => ({ id })),
      });
      if (created) {
        saved++;
        setBatchSavedCount(saved);
        if (draft.patient_id) savedPatientIds.push(draft.patient_id);
      }
    }

    // Auto-place the grounded patients into rooms (capacity-aware) per the chosen mode.
    if (savedPatientIds.length > 0) {
      await assignPatientRooms([...new Set(savedPatientIds)], batchRoomMode);
    }

    if (saved > 0) {
      await loadScenarios();
      const faculty = getCurrentFacultyUser();
      if (faculty) {
        logAuditAction({
          faculty_id: faculty.id,
          faculty_name: faculty.name,
          tab: "scenarios",
          action: "ai_generate_scenario_library",
          details: `AI generated and saved ${saved} scenario${saved === 1 ? "" : "s"}`,
          target_type: "scenario",
          target_id: "",
          metadata: {
            count: saved,
            requested: batchCount,
            topic: batchTopic.trim() || null,
            lesson: batchLesson.lesson?.fileName ?? null,
          },
        });
      }
      toast(`Saved ${saved} scenario${saved === 1 ? "" : "s"}`);
    }

    setBatchSaving(false);
    setShowBatchModal(false);
    setBatchDrafts(null);
    setBatchSelected([]);
  };

  const handleViewDetails = (scenario: SimulationScenario) => {
    setSelectedScenario(scenario);
    setShowDetailsModal(true);
  };

  const handleOpenAssignModal = (scenario: SimulationScenario) => {
    setSelectedScenario(scenario);
    setSelectedStudents([]);
    void fetchFacultyTeams().then((overview) =>
      setAssignHasTeams(
        Boolean(overview?.enabled && overview.teams.some((t) => t.members.length > 0)),
      ),
    );
    setAssignDeadline("");
    setAssignRequired(false);
    setStudentSearchQuery("");
    setShowAssignModal(true);
  };

  const toggleStudentSelection = (studentId: string) => {
    setSelectedStudents((prev) =>
      prev.includes(studentId) ? prev.filter((id) => id !== studentId) : [...prev, studentId],
    );
  };

  const handleAssignScenario = async () => {
    if (!selectedScenario || assignCount === 0 || !assignDeadline) return;

    setAssigning(true);
    const assignments = await assignScenarioToStudents(
      selectedScenario.id,
      selectedStudents,
      assignDeadline,
      assignRequired,
    );

    if (assignments.length > 0) {
      await loadScenarios();
      const faculty = getCurrentFacultyUser();
      if (faculty) {
        logAuditAction({
          faculty_id: faculty.id,
          faculty_name: faculty.name,
          tab: "scenarios",
          action: "assign_scenario",
          details: `Assigned patient case "${selectedScenario.title}" to ${assignments.length} student(s)`,
          target_type: "scenario",
          target_id: selectedScenario.id,
          metadata: {
            scenario_title: selectedScenario.title,
            student_count: assignments.length,
            required: assignRequired,
          },
        });
      }
      toast(`Assigned to ${assignments.length} student${assignments.length === 1 ? "" : "s"}`);
    } else {
      toast("Nobody new to assign — everyone chosen already has this patient case");
    }

    setAssigning(false);
    setShowAssignModal(false);
    setSelectedScenario(null);
    setSelectedStudents([]);
    setStudentSearchQuery("");
  };

  const handleOpenLinkPatientModal = (scenario: SimulationScenario) => {
    setLinkPatientTarget(scenario);
    setLinkPatientId(scenario.patient_id || "");
    setLinkPatientSearchQuery("");
    setShowLinkPatientModal(true);
    if (patients.length === 0) void loadPatientsForSelector();
  };

  const closeLinkPatientModal = () => {
    setShowLinkPatientModal(false);
    setLinkPatientTarget(null);
    setLinkPatientId("");
    setLinkPatientSearchQuery("");
  };

  const handleSavePatientLink = async () => {
    // Every scenario needs a patient, so this only ever switches to a
    // different one — the picker offers no "no linked patient" option.
    if (!linkPatientTarget || !linkPatientId) return;

    setSavingPatientLink(true);
    const updated = await updateScenario(linkPatientTarget.id, {
      patient_id: linkPatientId,
    });

    if (updated) {
      await loadScenarios();
      const faculty = getCurrentFacultyUser();
      if (faculty) {
        logAuditAction({
          faculty_id: faculty.id,
          faculty_name: faculty.name,
          tab: "scenarios",
          action: "link_scenario_patient",
          details: `Linked patient case "${linkPatientTarget.title}" to a patient`,
          target_type: "scenario",
          target_id: linkPatientTarget.id,
          metadata: { scenario_title: linkPatientTarget.title, patient_id: linkPatientId },
        });
      }
      toast("Patient linked");
    }

    setSavingPatientLink(false);
    closeLinkPatientModal();
  };

  const handleOpenDeleteModal = (scenario: SimulationScenario) => {
    setDeleteTarget(scenario);
    setDeleteError(null);
    setShowDeleteModal(true);
  };

  const closeDeleteModal = () => {
    if (deleting) return;
    setShowDeleteModal(false);
    setDeleteTarget(null);
    setDeleteError(null);
  };

  const handleConfirmDelete = async () => {
    if (!deleteTarget) return;

    setDeleting(true);
    setDeleteError(null);
    const ok = await deleteScenario(deleteTarget.id);

    if (!ok) {
      setDeleteError("Could not delete the patient case. Please try again.");
      setDeleting(false);
      return;
    }

    setData((previous) => ({
      scenarios: (previous?.scenarios ?? []).filter((s) => s.id !== deleteTarget.id),
      students: previous?.students ?? [],
    }));
    const faculty = getCurrentFacultyUser();
    if (faculty) {
      logAuditAction({
        faculty_id: faculty.id,
        faculty_name: faculty.name,
        tab: "scenarios",
        action: "delete_scenario",
        details: `Deleted patient case: ${deleteTarget.title}`,
        target_type: "scenario",
        target_id: deleteTarget.id,
        metadata: { scenario_title: deleteTarget.title },
      });
      toast("Patient case deleted");
    }

    setDeleting(false);
    setShowDeleteModal(false);
    setDeleteTarget(null);
  };

  const assignCount = selectedStudents.length;

  const filteredStudents = students.filter(
    (student) =>
      student.name.toLowerCase().includes(studentSearchQuery.toLowerCase()) ||
      student.email.toLowerCase().includes(studentSearchQuery.toLowerCase()),
  );

  const selectClassName =
    "w-full px-4 py-3 bg-surface border border-gray-400 rounded-xl text-gray-900 focus:outline-none focus:ring-2 focus:ring-brand-600/30 focus:border-brand-600 focus:bg-surface transition-all text-sm appearance-none shadow-sm cursor-pointer";

  return (
    <div>
      <PageHeader
        badge={{
          icon: <FontAwesomeIcon icon={faNotesMedical} className="w-3.5 h-3.5" />,
          label: "Patient Case Management",
        }}
        title="Patient Cases"
        subtitle="Manage patient cases for student training"
      />

      {/* Stats */}
      {loading ? (
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-4">
          {Array.from({ length: 3 }).map((_, i) => (
            <SkeletonStatTile key={i} />
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-4">
          <StatTile
            icon={faNotesMedical}
            value={scenarios.length}
            label="Total Patient Cases"
            iconBg="bg-brand-600/10"
            iconColor="text-brand-600"
          />
          <StatTile
            icon={faRobot}
            value={scenarios.filter((s) => s.is_ai_generated).length}
            label="AI Generated"
            iconBg="bg-brand-50"
            iconColor="text-brand-600"
          />
          <StatTile
            icon={faUsers}
            value={
              new Set(
                scenarios.flatMap(
                  (s) => (s as SimulationScenario & { student_ids?: string[] }).student_ids ?? [],
                ),
              ).size
            }
            label="Students Assigned"
            iconBg="bg-emerald-50"
            iconColor="text-emerald-600"
          />
        </div>
      )}

      {/* Filters */}
      {/* Wraps instead of overflowing: the filters shrink and wrap first, then
          the action buttons drop to their own right-aligned row. */}
      <div className="mb-4 flex flex-wrap items-center gap-3">
        <div className="flex min-w-0 flex-[1_1_36rem] flex-wrap items-center gap-3">
          <div className="relative min-w-0 max-w-md flex-[1_1_16rem]">
            <FontAwesomeIcon
              icon={faSearch}
              className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500"
            />
            <input
              type="text"
              placeholder="Search patient cases..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className={inputClassName + " pl-10"}
            />
          </div>
          <div className="relative min-w-0 flex-[1_1_10rem] sm:w-48 sm:flex-none">
            <FontAwesomeIcon
              icon={faHospitalUser}
              className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500"
            />
            <select
              value={categoryFilter}
              onChange={(e) => setCategoryFilter(e.target.value)}
              className={selectClassName + " pl-10 pr-10 w-full"}
            >
              <option value="all">All Categories</option>
              {categories.map((cat) => (
                <option key={cat} value={cat}>
                  {cat}
                </option>
              ))}
            </select>
            <FontAwesomeIcon
              icon={faChevronDown}
              className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500 pointer-events-none"
            />
          </div>
        </div>
        <div className="ml-auto flex min-w-0 basis-full flex-wrap justify-end gap-2 sm:basis-auto">
          <button
            onClick={openBatchModal}
            className="group flex flex-1 items-center justify-center gap-2 whitespace-nowrap rounded-xl sm:flex-none border border-brand-700/25 bg-surface px-4 py-2.5 text-sm font-semibold text-brand-800 transition-all hover:border-brand-700/40 hover:bg-brand-50"
          >
            <FontAwesomeIcon
              icon={faLayerGroup}
              className="w-4 h-4 text-brand-600 transition-transform group-hover:scale-110"
            />
            Generate Library
          </button>
          <button
            onClick={() => router.push("/faculty/scenarios/review")}
            className="group flex flex-1 items-center justify-center gap-2 whitespace-nowrap rounded-xl sm:flex-none border border-gray-300 bg-surface px-4 py-2.5 text-sm font-semibold text-gray-700 transition-all hover:border-brand-300 hover:bg-brand-50"
          >
            <FontAwesomeIcon
              icon={faListCheck}
              className="w-4 h-4 text-brand-600 transition-transform group-hover:scale-110"
            />
            Review cases
          </button>
          <button
            onClick={() => router.push("/faculty/scenarios/new")}
            className="flex flex-1 items-center justify-center gap-2 whitespace-nowrap rounded-xl bg-brand-600 sm:flex-none px-4 py-2.5 text-sm font-semibold text-white shadow-[0_2px_8px_-1px_rgb(27_107_123_/_0.35)] transition-all hover:bg-brand-700 hover:shadow-[0_4px_14px_-2px_rgb(27_107_123_/_0.45)]"
          >
            <FontAwesomeIcon icon={faPlus} className="w-4 h-4" />
            Create Patient Case
          </button>
        </div>
      </div>

      {/* Patient Cases Grid */}
      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {Array.from({ length: 6 }).map((_, i) => (
            <SkeletonScenarioCard key={i} />
          ))}
        </div>
      ) : filteredScenarios.length === 0 ? (
        <div className="bg-surface rounded-xl border border-hairline shadow-[0_1px_3px_0_rgba(0,0,0,0.04),0_1px_2px_-1px_rgba(0,0,0,0.06)] p-12 text-center">
          <FontAwesomeIcon icon={faNotesMedical} className="w-12 h-12 text-gray-300 mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-gray-700">No patient cases found</h3>
          <p className="text-gray-500 text-sm mt-1">
            {searchQuery || categoryFilter !== "all"
              ? "Try adjusting your filters."
              : "Generate a starter library, or create your first patient case by hand."}
          </p>
          {!searchQuery && categoryFilter === "all" && (
            <button
              onClick={openBatchModal}
              className="mt-4 inline-flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-brand-600 to-brand-800 text-white font-medium rounded-xl hover:from-brand-700 hover:to-brand-900 transition-all shadow-lg shadow-[0_4px_14px_-2px_rgb(27_107_123_/_0.45)]"
            >
              <FontAwesomeIcon icon={faLayerGroup} className="w-4 h-4" />
              Generate Library
            </button>
          )}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredScenarios.map((scenario) => (
            <div
              key={scenario.id}
              className="group bg-surface rounded-xl border border-hairline shadow-[0_1px_3px_0_rgba(0,0,0,0.04),0_1px_2px_-1px_rgba(0,0,0,0.06)] hover:shadow-[0_4px_12px_0_rgba(0,0,0,0.06),0_2px_4px_-2px_rgba(0,0,0,0.06)] hover:border-gray-200 transition-all duration-200 overflow-hidden flex flex-col"
            >
              <div className="p-3 border-b border-hairline flex-1">
                <div className="flex items-start justify-between mb-3">
                  <h3 className="font-semibold text-gray-900 line-clamp-2 pr-2">
                    {scenario.title}
                  </h3>
                  {scenario.is_ai_generated && (
                    <span className="px-2 py-1 bg-brand-100 text-brand-700 text-xs font-medium rounded-full flex items-center gap-1 whitespace-nowrap">
                      <FontAwesomeIcon icon={faRobot} className="w-3 h-3" />
                      AI
                    </span>
                  )}
                </div>
                <p className="text-sm text-gray-500 line-clamp-2 mb-4">{scenario.description}</p>
                <div className="flex items-center gap-2 flex-wrap">
                  <span className="px-2.5 py-1 bg-gray-100 text-gray-700 text-xs font-medium rounded-full">
                    {scenario.category}
                  </span>
                  {scenario.patient_name && (
                    <span className="px-2.5 py-1 bg-teal-50 text-teal-700 text-xs font-medium rounded-full flex items-center gap-1">
                      <FontAwesomeIcon icon={faUsers} className="w-3 h-3" />
                      {scenario.patient_name}
                    </span>
                  )}
                </div>
              </div>
              <div className="p-5 bg-subtle">
                <div className="flex items-center justify-between text-sm mb-4">
                  <span className="text-gray-500 flex items-center gap-1.5">
                    <FontAwesomeIcon icon={faUsers} className="w-3.5 h-3.5" />
                    {scenario.student_count} students
                  </span>
                  <span className="text-gray-400 flex items-center gap-1.5">
                    <FontAwesomeIcon icon={faCalendarDay} className="w-3.5 h-3.5" />
                    {new Date(scenario.created_at).toLocaleDateString()}
                  </span>
                </div>
                <ActionsMenu
                  actions={[
                    { label: "View", icon: faEye, onClick: () => handleViewDetails(scenario) },
                    {
                      label: "Edit",
                      icon: faPenToSquare,
                      onClick: () => router.push(`/faculty/scenarios/${scenario.id}/edit`),
                    },
                    {
                      label: "Assign",
                      icon: faUserPlus,
                      onClick: () => handleOpenAssignModal(scenario),
                    },
                    {
                      label: scenario.patient_name ? "Change patient" : "Link patient",
                      icon: faHospitalUser,
                      onClick: () => handleOpenLinkPatientModal(scenario),
                    },
                    {
                      label: "Delete",
                      icon: faTrash,
                      danger: true,
                      onClick: () => handleOpenDeleteModal(scenario),
                    },
                  ]}
                />
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Delete Patient Case Modal */}
      {showDeleteModal && deleteTarget && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-surface rounded-xl w-full max-w-md overflow-hidden shadow-[0_8px_30px_rgba(0,0,0,0.12)] border border-hairline">
            <div className="p-5">
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 rounded-lg bg-rose-50 flex items-center justify-center shrink-0">
                  <FontAwesomeIcon icon={faTrash} className="w-5 h-5 text-rose-600" />
                </div>
                <div className="min-w-0">
                  <h3 className="text-lg font-bold text-gray-900">Delete patient case?</h3>
                  <p className="text-sm text-gray-500 mt-1">
                    <span className="font-medium text-gray-700">{deleteTarget.title}</span> will be
                    permanently removed. This can&apos;t be undone.
                  </p>
                  {deleteTarget.student_count > 0 && (
                    <div className="mt-3 flex items-start gap-2 rounded-lg border border-amber-200 bg-amber-50 p-2.5 text-xs text-amber-800">
                      <FontAwesomeIcon
                        icon={faTriangleExclamation}
                        className="w-3.5 h-3.5 mt-0.5 shrink-0"
                      />
                      <span>
                        {`Assigned to ${deleteTarget.student_count} student${
                          deleteTarget.student_count === 1 ? "" : "s"
                        }. Their assignments will be removed too.`}
                      </span>
                    </div>
                  )}
                  {deleteError && (
                    <div className="mt-3 p-2.5 rounded-lg bg-red-50 text-red-700 text-xs border border-red-200">
                      {deleteError}
                    </div>
                  )}
                </div>
              </div>
              <div className="flex justify-end gap-3 mt-5">
                <button
                  type="button"
                  onClick={closeDeleteModal}
                  disabled={deleting}
                  className="px-5 py-2.5 bg-surface border border-gray-200 hover:bg-gray-50 rounded-lg text-sm font-medium text-gray-700 transition-all disabled:opacity-50"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleConfirmDelete}
                  disabled={deleting}
                  className="px-5 py-2.5 bg-rose-600 text-white rounded-lg font-medium hover:bg-rose-700 transition-all disabled:opacity-50 flex items-center gap-2 shadow-[0_2px_6px_rgba(225,29,72,0.25)]"
                >
                  {deleting ? (
                    <EcgLoader />
                  ) : (
                    <FontAwesomeIcon icon={faTrash} className="w-4 h-4" />
                  )}
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Generate Library Modal */}
      {showBatchModal && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-3 sm:p-4">
          <div
            role="dialog"
            aria-modal="true"
            aria-labelledby="library-modal-title"
            className="bg-surface rounded-2xl w-full max-w-5xl max-h-[90vh] overflow-hidden flex flex-col shadow-[0_24px_60px_-12px_rgba(0,0,0,0.35)] border border-hairline animate-rise"
          >
            <header className="relative shrink-0 px-5 pt-5 pb-4 border-b border-hairline overflow-hidden">
              {/* A faint ECG trace behind the title: the library is a ward's worth of patients. */}
              <svg
                aria-hidden
                viewBox="0 0 600 60"
                preserveAspectRatio="none"
                className="pointer-events-none absolute inset-x-0 bottom-0 h-14 w-full text-brand-600/[0.07]"
              >
                <path
                  d="M0 40 H170 l10 -6 l8 6 H232 l6 -30 l8 44 l7 -24 l5 10 H330 l10 -6 l8 6 H600"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2.5"
                />
              </svg>
              <div className="relative flex items-start justify-between gap-4">
                <div className="min-w-0">
                  <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-brand-600">
                    Patient case library
                  </p>
                  <h3
                    id="library-modal-title"
                    className="font-display text-2xl font-semibold text-gray-900 mt-1"
                  >
                    {batchDrafts ? "Pick the cases to keep" : "Plan a library"}
                  </h3>
                  <ol className="flex items-center gap-2 mt-3 text-xs" aria-label="Progress">
                    {["Plan", "Review & save"].map((label, i) => {
                      const current = (batchDrafts ? 1 : 0) === i;
                      const done = !!batchDrafts && i === 0;
                      return (
                        <li key={label} className="flex items-center gap-2">
                          {i > 0 && <span className="w-6 h-px bg-gray-300" aria-hidden />}
                          <span
                            aria-current={current ? "step" : undefined}
                            className={`inline-flex items-center gap-1.5 font-medium ${
                              current ? "text-gray-900" : "text-gray-400"
                            }`}
                          >
                            <span
                              className={`w-4 h-4 rounded-full flex items-center justify-center text-[10px] font-semibold ${
                                current
                                  ? "bg-brand-600 text-white"
                                  : done
                                    ? "bg-brand-100 text-brand-700"
                                    : "bg-gray-200 text-gray-500"
                              }`}
                            >
                              {done ? <FontAwesomeIcon icon={faCheck} className="w-2 h-2" /> : i + 1}
                            </span>
                            {label}
                          </span>
                        </li>
                      );
                    })}
                  </ol>
                </div>
                <button
                  onClick={closeBatchModal}
                  disabled={batchGenerating || batchSaving}
                  aria-label="Close"
                  className="p-2 -mr-1 hover:bg-subtle rounded-lg transition-colors disabled:opacity-40"
                >
                  <FontAwesomeIcon icon={faTimes} className="w-5 h-5 text-gray-500" />
                </button>
              </div>
            </header>

            {!batchDrafts ? (
              <div className="flex-1 overflow-y-auto lg:overflow-hidden lg:grid lg:grid-cols-[1fr_300px]">
                <div className="p-5 space-y-7 lg:overflow-y-auto">
                  <Step
                    n={1}
                    title="Lesson"
                    hint="Optional. The Taylor's chapters a lesson covers are picked for you, and every case applies it."
                  >
                    <div className="space-y-2">
                      {!batchLesson.lesson && !batchLesson.analyzing ? (
                        <button
                          type="button"
                          onClick={batchLesson.pick}
                          disabled={batchGenerating}
                          className="group w-full flex items-center gap-3 rounded-xl border border-dashed border-gray-300 bg-subtle/60 px-4 py-3.5 text-left transition-all hover:border-brand-400 hover:bg-brand-50/60 disabled:opacity-50"
                        >
                          <span className="w-9 h-9 rounded-lg bg-surface border border-hairline flex items-center justify-center text-brand-600 group-hover:border-brand-300 transition-colors">
                            <FontAwesomeIcon icon={faFileImport} className="w-4 h-4" />
                          </span>
                          <span>
                            <span className="block text-sm font-semibold text-gray-800">Import a lesson</span>
                            <span className="block text-xs text-gray-500">PDF, Word, text or Markdown</span>
                          </span>
                        </button>
                      ) : (
                        <button
                          type="button"
                          onClick={batchLesson.pick}
                          disabled={batchGenerating}
                          className="text-xs font-medium text-brand-700 hover:text-brand-900 disabled:opacity-50"
                        >
                          <FontAwesomeIcon icon={faFileImport} className="w-3 h-3 mr-1.5" />
                          Change lesson
                        </button>
                      )}
                      {batchLesson.fileInput}
                      <LessonPanel lessonImport={batchLesson} disabled={batchGenerating}>
                        <p className="text-xs text-gray-500">
                          The library cycles through the ticked chapters.
                        </p>
                      </LessonPanel>
                    </div>
                  </Step>

                  <Step
                    n={2}
                    title="Chapters"
                    hint={
                      batchUsesTopics
                        ? "Set by the lesson above: tick or untick its chapters there."
                        : batchChapters.length === 0
                          ? "None picked, so the library spreads across all three."
                          : `The library cycles through the ${batchChapters.length} picked.`
                    }
                  >
                    {!batchUsesTopics && (
                      <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">
                        {TAUGHT_CHAPTERS.map((c) => (
                          <ChapterCard
                            key={c.chapter}
                            chapter={c}
                            selected={batchChapters.includes(c.chapter)}
                            disabled={batchGenerating}
                            onToggle={() => toggleBatchChapter(c.chapter)}
                          />
                        ))}
                      </div>
                    )}
                  </Step>

                  <Step n={3} title="Teaching focus" hint="Optional. Steers every case toward one theme.">
                    <input
                      type="text"
                      value={batchTopic}
                      onChange={(e) => setBatchTopic(e.target.value)}
                      disabled={batchGenerating}
                      placeholder="e.g. post-operative care for second-year students"
                      className={inputClassName}
                    />
                  </Step>

                  <Step
                    n={4}
                    title="Room placement"
                    hint="Saved cases' patients go into rooms without going over capacity; any overflow stays unassigned."
                  >
                    <div className="flex flex-col sm:flex-row gap-2" role="radiogroup" aria-label="Room placement">
                      <RoomModeCard
                        mode="fill"
                        title="Fill rooms"
                        hint="Pack each room before the next"
                        selected={batchRoomMode === "fill"}
                        disabled={batchGenerating}
                        onSelect={() => setBatchRoomMode("fill")}
                      />
                      <RoomModeCard
                        mode="spread"
                        title="Spread evenly"
                        hint="Balance patients across rooms"
                        selected={batchRoomMode === "spread"}
                        disabled={batchGenerating}
                        onSelect={() => setBatchRoomMode("spread")}
                      />
                    </div>
                  </Step>
                </div>

                <aside className="border-t lg:border-t-0 lg:border-l border-hairline bg-subtle/70 p-5 lg:overflow-y-auto">
                  <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-gray-500">
                    Library plan
                  </p>

                  <div className="mt-3 flex items-center justify-between gap-2">
                    <button
                      type="button"
                      onClick={() => {
                        const n = Math.max(1, batchCount - 1);
                        setBatchCount(n);
                        setBatchCountInput(String(n));
                      }}
                      disabled={batchGenerating || batchCount <= 1}
                      aria-label="One fewer patient case"
                      className="w-9 h-9 rounded-full border border-gray-300 bg-surface text-gray-600 hover:border-brand-400 hover:text-brand-700 transition-colors disabled:opacity-40"
                    >
                      <FontAwesomeIcon icon={faMinus} className="w-3 h-3" />
                    </button>
                    <label className="flex-1 text-center">
                      <input
                        type="number"
                        min={1}
                        value={batchCountInput}
                        onChange={(e) => {
                          // Show exactly what's typed (including empty); commit the
                          // count only when it parses to a valid whole number ≥ 1.
                          setBatchCountInput(e.target.value);
                          const n = parseInt(e.target.value, 10);
                          if (!Number.isNaN(n) && n >= 1) setBatchCount(n);
                        }}
                        onBlur={() => setBatchCountInput(String(batchCount))}
                        disabled={batchGenerating}
                        aria-label="Number of scenarios to generate"
                        className="w-full bg-transparent text-center font-display text-5xl font-semibold tabular-nums text-gray-900 focus:outline-none [appearance:textfield] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none"
                      />
                      <span className="block text-xs text-gray-500 -mt-0.5">
                        patient case{batchCount === 1 ? "" : "s"}
                      </span>
                    </label>
                    <button
                      type="button"
                      onClick={() => {
                        const n = batchCount + 1;
                        setBatchCount(n);
                        setBatchCountInput(String(n));
                      }}
                      disabled={batchGenerating}
                      aria-label="One more patient case"
                      className="w-9 h-9 rounded-full border border-gray-300 bg-surface text-gray-600 hover:border-brand-400 hover:text-brand-700 transition-colors disabled:opacity-40"
                    >
                      <FontAwesomeIcon icon={faPlus} className="w-3 h-3" />
                    </button>
                  </div>

                  <div className="mt-5">
                    <PlanStrip key={planSequence.length} sequence={planSequence} />
                  </div>
                  <div className="mt-3">
                    <PlanLegend sequence={planSequence} />
                  </div>

                  <dl className="mt-5 pt-4 border-t border-hairline space-y-3 text-xs">
                    <div className="flex gap-2.5">
                      <FontAwesomeIcon icon={faHospitalUser} className="w-3.5 h-3.5 mt-0.5 text-brand-600 shrink-0" />
                      <div>
                        <dt className="font-semibold text-gray-800">A roster patient each</dt>
                        <dd className="text-gray-500">
                          The case is written around that patient&apos;s diagnosis and vital signs.
                        </dd>
                      </div>
                    </div>
                    <div className="flex gap-2.5">
                      <FontAwesomeIcon icon={faClock} className="w-3.5 h-3.5 mt-0.5 text-brand-600 shrink-0" />
                      <div>
                        <dt className="font-semibold text-gray-800">
                          {batchCount <= MAX_PER_REQUEST
                            ? "About a minute"
                            : `About ${Math.ceil(batchCount / MAX_PER_REQUEST)} minutes`}
                        </dt>
                        <dd className="text-gray-500">
                          {batchCount <= MAX_PER_REQUEST
                            ? "Nothing is saved until you pick the cases to keep."
                            : `Written in batches of ${MAX_PER_REQUEST}. Nothing is saved until you pick the cases to keep.`}
                        </dd>
                      </div>
                    </div>
                  </dl>

                  {batchError && (
                    <div className="mt-4 p-3 rounded-lg text-xs border bg-red-50 text-red-700 border-red-200 flex items-start gap-2">
                      <FontAwesomeIcon icon={faTriangleExclamation} className="w-3.5 h-3.5 mt-0.5 shrink-0" />
                      {batchError}
                    </div>
                  )}
                </aside>

                {batchGenerating && (
                  <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-[60] p-4">
                    <div className="bg-surface rounded-2xl w-full max-w-md p-7 shadow-[0_24px_60px_-12px_rgba(0,0,0,0.35)] border border-hairline animate-rise">
                      <div className="flex items-center gap-3">
                        <EcgLoader size="lg" className="text-brand-600" />
                        <div>
                          <p className="font-display text-lg font-semibold text-gray-900">
                            {batchCancelling ? "Stopping…" : "Writing patient cases"}
                          </p>
                          <p className="text-xs text-gray-500 tabular-nums">
                            {batchCancelling
                              ? `Keeping the ${batchProgress} written so far.`
                              : `${batchProgress} of ${batchCount} ready`}
                          </p>
                        </div>
                      </div>
                      <div className="mt-5">
                        <PlanStrip sequence={planSequence} filled={batchProgress} size="lg" />
                      </div>
                      <p className="text-xs text-gray-500 mt-4">
                        {batchCount > MAX_PER_REQUEST
                          ? `Cases arrive in batches of ${MAX_PER_REQUEST}; this can take a few minutes.`
                          : "This takes up to a minute."}
                      </p>
                      <button
                        type="button"
                        onClick={cancelBatch}
                        disabled={batchCancelling}
                        className="mt-5 w-full inline-flex items-center justify-center gap-2 px-5 py-2.5 bg-surface border border-gray-300 text-gray-700 rounded-lg font-medium hover:bg-subtle transition-all disabled:opacity-50"
                      >
                        {batchCancelling ? (
                          <>
                            <EcgLoader />
                            Stopping…
                          </>
                        ) : (
                          <>
                            <FontAwesomeIcon icon={faTimes} className="w-4 h-4" />
                            Stop and keep what&apos;s written
                          </>
                        )}
                      </button>
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div className="flex-1 overflow-y-auto p-5 space-y-4">
                {batchWarning && (
                  <div className="p-3 rounded-lg text-sm border bg-amber-50 text-amber-700 border-amber-200 flex items-start gap-2">
                    <FontAwesomeIcon icon={faTriangleExclamation} className="w-4 h-4 mt-0.5 shrink-0" />
                    {batchWarning}
                  </div>
                )}
                <div className="flex items-center justify-between gap-3">
                  <p className="text-sm text-gray-600">
                    <span className="font-display text-xl font-semibold text-gray-900 tabular-nums">
                      {batchSelected.length}
                    </span>{" "}
                    of {batchDrafts.length} selected
                  </p>
                  <button
                    type="button"
                    onClick={() =>
                      setBatchSelected(
                        batchSelected.length === batchDrafts.length ? [] : batchDrafts.map((_, i) => i),
                      )
                    }
                    disabled={batchSaving}
                    className="text-sm font-medium text-brand-700 hover:text-brand-900 disabled:opacity-50"
                  >
                    {batchSelected.length === batchDrafts.length ? "Deselect all" : "Select all"}
                  </button>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {batchDrafts.map((draft, i) => {
                    const checked = batchSelected.includes(i);
                    const patientName = draft.patient_id
                      ? patients.find((p) => p.id === draft.patient_id)?.name
                      : null;
                    return (
                      <label
                        key={i}
                        style={{ ...hueStyle(draft.chapter), animationDelay: `${Math.min(i, 12) * 40}ms` }}
                        className={`relative flex flex-col gap-2 pl-5 pr-4 py-4 rounded-xl border cursor-pointer overflow-hidden transition-all animate-rise ${
                          checked
                            ? "border-[color-mix(in_srgb,var(--hue)_55%,transparent)] bg-[color-mix(in_srgb,var(--hue)_5%,transparent)]"
                            : "border-hairline bg-surface opacity-70 hover:opacity-100"
                        }`}
                      >
                        <span aria-hidden className="absolute left-0 inset-y-0 w-1 bg-[var(--hue)]" />
                        <span className="flex items-start justify-between gap-3">
                          <span className="text-[11px] font-semibold uppercase tracking-[0.08em] text-[var(--hue)]">
                            {draft.chapter ? `Chapter ${draft.chapter} · ${chapterName(draft.chapter)}` : "Patient case"}
                          </span>
                          <input
                            type="checkbox"
                            checked={checked}
                            disabled={batchSaving}
                            onChange={() =>
                              setBatchSelected((prev) =>
                                prev.includes(i) ? prev.filter((x) => x !== i) : [...prev, i],
                              )
                            }
                            className="w-4 h-4 accent-brand-600 shrink-0"
                          />
                        </span>
                        <span className="font-semibold text-gray-900 leading-snug">{draft.title}</span>
                        <span className="text-sm text-gray-500 line-clamp-3">{draft.description}</span>
                        <span className="flex items-center gap-3 flex-wrap mt-auto pt-1 text-xs text-gray-500">
                          {patientName && (
                            <span className="inline-flex items-center gap-1.5 font-medium text-gray-700">
                              <FontAwesomeIcon icon={faHospitalUser} className="w-3 h-3 text-brand-600" />
                              {patientName}
                            </span>
                          )}
                          <span>{draft.learning_objectives.length} objectives</span>
                          {(draft.skills?.length ?? 0) > 0 && (
                            <span className="tabular-nums">Skills {draft.skills!.join(", ")}</span>
                          )}
                        </span>
                      </label>
                    );
                  })}
                </div>
              </div>
            )}

            <footer className="shrink-0 px-5 py-3.5 border-t border-hairline bg-subtle flex items-center justify-end gap-3">
              {!batchDrafts ? (
                batchGenerating ? (
                  <button
                    type="button"
                    onClick={cancelBatch}
                    disabled={batchCancelling}
                    className="px-5 py-2.5 bg-surface border border-gray-300 text-gray-700 rounded-lg font-medium hover:bg-gray-50 transition-all disabled:opacity-50 flex items-center gap-2"
                  >
                    {batchCancelling ? (
                      <>
                        <EcgLoader />
                        Stopping…
                      </>
                    ) : (
                      <>
                        <FontAwesomeIcon icon={faTimes} className="w-4 h-4" />
                        Stop
                      </>
                    )}
                  </button>
                ) : (
                  <>
                    <button
                      type="button"
                      onClick={closeBatchModal}
                      className="hidden sm:inline px-4 py-2.5 text-sm font-medium text-gray-600 hover:text-gray-900 transition-colors"
                    >
                      Cancel
                    </button>
                    <button
                      type="button"
                      onClick={handleGenerateBatch}
                      disabled={
                        !!batchLesson.analyzing ||
                        (batchUsesTopics && batchLesson.selectedTopics.length === 0)
                      }
                      className="w-full sm:w-auto justify-center whitespace-nowrap px-5 py-2.5 bg-gradient-to-r from-brand-600 to-brand-800 text-white rounded-lg font-medium hover:from-brand-700 hover:to-brand-900 transition-all flex items-center gap-2 shadow-[0_4px_14px_-2px_rgb(27_107_123_/_0.45)] disabled:opacity-50"
                    >
                      <FontAwesomeIcon icon={faLayerGroup} className="w-4 h-4" />
                      Generate {batchCount} Patient Case{batchCount === 1 ? "" : "s"}
                    </button>
                  </>
                )
              ) : (
                <>
                  <button
                    type="button"
                    onClick={handleGenerateBatch}
                    disabled={batchSaving}
                    className="px-5 py-2.5 bg-surface border border-brand-300 text-brand-700 rounded-lg font-medium hover:bg-brand-50 transition-all disabled:opacity-50"
                  >
                    Regenerate
                  </button>
                  <button
                    type="button"
                    onClick={handleSaveBatch}
                    disabled={batchSaving || batchSelected.length === 0}
                    className="px-5 py-2.5 bg-brand-600 text-white rounded-lg font-medium hover:bg-brand-700 transition-all disabled:opacity-50 flex items-center gap-2 shadow-[0_2px_6px_rgba(27,107,123,0.2)]"
                  >
                    {batchSaving ? (
                      <>
                        <EcgLoader />
                        Saving {batchSavedCount}/{batchSelected.length}…
                      </>
                    ) : (
                      `Save ${batchSelected.length} Patient Case${batchSelected.length === 1 ? "" : "s"}`
                    )}
                  </button>
                </>
              )}
            </footer>
          </div>
        </div>
      )}

      {/* Details Modal */}
      {showDetailsModal && selectedScenario && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-surface rounded-xl w-full max-w-3xl max-h-[85vh] overflow-hidden flex flex-col shadow-[0_8px_30px_rgba(0,0,0,0.12)] border border-hairline">
            <div className="p-4 border-b border-hairline bg-subtle">
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-3 flex-wrap">
                    <div className="w-10 h-10 bg-brand-600/10 rounded-lg flex items-center justify-center">
                      <FontAwesomeIcon icon={faNotesMedical} className="text-brand-600 w-5 h-5" />
                    </div>
                    <h2 className="text-2xl font-bold text-gray-900">{selectedScenario.title}</h2>
                    {selectedScenario.is_ai_generated && (
                      <span className="px-2.5 py-1 bg-brand-100 text-brand-700 text-xs font-semibold rounded-full flex items-center gap-1">
                        <FontAwesomeIcon icon={faRobot} className="w-3 h-3" />
                        AI Generated
                      </span>
                    )}
                  </div>
                  <p className="text-gray-600">{selectedScenario.description}</p>
                </div>
                <button
                  onClick={() => setShowDetailsModal(false)}
                  className="p-2 hover:bg-gray-200 rounded-lg transition-colors"
                >
                  <FontAwesomeIcon icon={faTimes} className="w-5 h-5 text-gray-500" />
                </button>
              </div>
              <div className="flex items-center gap-3 mt-4 flex-wrap">
                <span className="px-3 py-1 bg-gray-100 text-gray-700 text-sm font-semibold rounded-full">
                  {selectedScenario.category}
                </span>
                <span className="text-sm text-gray-500 flex items-center gap-1">
                  <FontAwesomeIcon icon={faUsers} className="w-3.5 h-3.5" />
                  {selectedScenario.student_count} students
                </span>
                <span className="text-sm text-gray-400 flex items-center gap-1">
                  <FontAwesomeIcon icon={faCalendarDay} className="w-3.5 h-3.5" />
                  Created: {new Date(selectedScenario.created_at).toLocaleDateString()}
                </span>
              </div>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar">
              <div>
                <h3 className="text-lg font-bold text-gray-900 mb-3 flex items-center gap-2">
                  <FontAwesomeIcon icon={faStethoscope} className="text-brand-600" />
                  Patient Case
                </h3>
                <div className="bg-gray-50 rounded-xl p-5 border border-gray-200">
                  {selectedScenario.patient_case ? (
                    <div className="space-y-4">
                      {selectedScenario.patient_case.chief_complaint && (
                        <div className="bg-red-50 border border-red-200 rounded-xl p-4">
                          <p className="text-sm font-bold text-red-700 mb-1 flex items-center gap-2">
                            <FontAwesomeIcon icon={faExclamationTriangle} className="w-4 h-4" />
                            Chief Complaint
                          </p>
                          <p className="text-gray-800">
                            {selectedScenario.patient_case.chief_complaint}
                          </p>
                        </div>
                      )}
                      {selectedScenario.patient_case.vitals && (
                        <div>
                          <p className="text-sm font-bold text-gray-600 mb-2 flex items-center gap-2">
                            <FontAwesomeIcon icon={faHeartbeat} className="w-4 h-4 text-red-600" />
                            Vital Signs
                          </p>
                          <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
                            {Object.entries(selectedScenario.patient_case.vitals).map(
                              ([key, value]) => (
                                <div
                                  key={key}
                                  className="bg-surface rounded-lg p-3 border border-gray-200"
                                >
                                  <p className="text-xs text-gray-500 capitalize">
                                    {key.replace(/_/g, " ")}
                                  </p>
                                  <p className="font-semibold text-gray-800">{String(value)}</p>
                                </div>
                              ),
                            )}
                          </div>
                        </div>
                      )}
                      {selectedScenario.patient_case.medical_history && (
                        <div>
                          <p className="text-sm font-bold text-gray-600 mb-1">Medical History</p>
                          <p className="text-gray-800">
                            {selectedScenario.patient_case.medical_history}
                          </p>
                        </div>
                      )}
                      {selectedScenario.patient_case.physical_exam && (
                        <div>
                          <p className="text-sm font-bold text-gray-600 mb-1">
                            Physical Examination
                          </p>
                          <p className="text-gray-800">
                            {selectedScenario.patient_case.physical_exam}
                          </p>
                        </div>
                      )}
                      {selectedScenario.patient_case.diagnosis && (
                        <div>
                          <p className="text-sm font-bold text-gray-600 mb-1">Diagnosis</p>
                          <p className="text-gray-800">{selectedScenario.patient_case.diagnosis}</p>
                        </div>
                      )}
                      {selectedScenario.patient_case.treatment_plan && (
                        <div>
                          <p className="text-sm font-bold text-gray-600 mb-1">Treatment Plan</p>
                          <p className="text-gray-800">
                            {selectedScenario.patient_case.treatment_plan}
                          </p>
                        </div>
                      )}
                    </div>
                  ) : (
                    <p className="text-gray-500">No patient case details available</p>
                  )}
                </div>
              </div>

              <div>
                <h3 className="text-lg font-bold text-gray-900 mb-3 flex items-center gap-2">
                  <FontAwesomeIcon icon={faListCheck} className="text-brand-600" />
                  Learning Objectives
                </h3>
                <ul className="space-y-2">
                  {selectedScenario.learning_objectives &&
                  selectedScenario.learning_objectives.length > 0 ? (
                    selectedScenario.learning_objectives.map((objective, index) => (
                      <li key={index} className="flex items-start gap-3">
                        <div className="w-6 h-6 rounded-full bg-brand-600/10 flex items-center justify-center flex-shrink-0 mt-0.5">
                          <span className="text-sm font-bold text-brand-600">{index + 1}</span>
                        </div>
                        <p className="text-gray-700">{objective}</p>
                      </li>
                    ))
                  ) : (
                    <p className="text-gray-500">No learning objectives defined</p>
                  )}
                </ul>
              </div>
            </div>

            <div className="p-4 border-t border-hairline bg-subtle">
              <div className="flex justify-end gap-3">
                <button
                  onClick={() => setShowDetailsModal(false)}
                  className="px-5 py-2.5 bg-surface border border-gray-200 hover:bg-gray-50 rounded-lg text-sm font-medium text-gray-700 transition-all"
                >
                  Close
                </button>
                <button
                  onClick={() => {
                    setShowDetailsModal(false);
                    handleOpenAssignModal(selectedScenario);
                  }}
                  className="px-5 py-2.5 bg-brand-600 text-white rounded-lg font-medium hover:bg-brand-700 transition-all flex items-center gap-2 shadow-[0_2px_6px_rgba(27,107,123,0.2)]"
                >
                  <FontAwesomeIcon icon={faUserPlus} className="w-4 h-4" />
                  Assign to Students
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Assign Modal */}
      {showAssignModal && selectedScenario && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-surface rounded-xl w-full max-w-4xl max-h-[85vh] overflow-hidden flex flex-col shadow-[0_8px_30px_rgba(0,0,0,0.12)] border border-hairline">
            <div className="p-4 border-b border-hairline bg-subtle">
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-brand-600/10 rounded-lg flex items-center justify-center">
                    <FontAwesomeIcon icon={faUserPlus} className="text-brand-600 w-5 h-5" />
                  </div>
                  <div>
                    <h2 className="text-lg font-bold text-gray-900">Assign Patient Case</h2>
                    <p className="text-sm text-gray-500">{selectedScenario.title}</p>
                  </div>
                </div>
                <button
                  onClick={() => setShowAssignModal(false)}
                  className="p-2 hover:bg-gray-200 rounded-lg transition-colors"
                >
                  <FontAwesomeIcon icon={faTimes} className="w-5 h-5 text-gray-500" />
                </button>
              </div>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar">
              <div className="bg-gray-50 rounded-xl p-4 border border-gray-200">
                <h3 className="text-sm font-bold text-gray-900 mb-3 flex items-center gap-2">
                  <FontAwesomeIcon icon={faCalendarDay} className="text-brand-600" />
                  Assignment Settings
                </h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className={labelClassName}>Deadline</label>
                    <div className="relative">
                      <FontAwesomeIcon
                        icon={faCalendarDay}
                        className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500"
                      />
                      <input
                        type="date"
                        value={assignDeadline}
                        onChange={(e) => setAssignDeadline(e.target.value)}
                        className={inputClassName + " pl-10"}
                      />
                    </div>
                  </div>
                  <div className="flex items-center pt-7">
                    <label className="flex items-center gap-3 cursor-pointer p-3 rounded-xl border border-gray-200 bg-surface hover:bg-gray-50 transition-colors w-full">
                      <input
                        type="checkbox"
                        checked={assignRequired}
                        onChange={(e) => setAssignRequired(e.target.checked)}
                        className="w-5 h-5 text-brand-600 rounded focus:ring-brand-600"
                      />
                      <span className="text-sm font-semibold text-gray-700">
                        Required for all students
                      </span>
                    </label>
                  </div>
                </div>
              </div>

              {assignHasTeams && (
                <p className="flex items-start gap-2 rounded-xl border border-hairline bg-subtle px-3 py-2 text-xs text-gray-600">
                  <FontAwesomeIcon icon={faUsers} className="mt-0.5 h-3.5 w-3.5 text-brand-600" />
                  <span>
                    To give a whole group work, use <strong>Assign case</strong> on the Groups page.
                    The group shares one case and each member is graded on their own.
                  </span>
                </p>
              )}

              <div>
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-sm font-bold text-gray-900 flex items-center gap-2">
                    <FontAwesomeIcon icon={faUser} className="text-brand-600" />
                    Select Students
                  </h3>
                  <button
                    onClick={() => setSelectedStudents(filteredStudents.map((s) => s.id))}
                    className="text-sm text-brand-600 hover:text-brand-700 font-semibold"
                  >
                    Select All
                  </button>
                </div>
                <div className="mb-3">
                  <div className="relative">
                    <FontAwesomeIcon
                      icon={faSearch}
                      className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-500"
                    />
                    <input
                      type="text"
                      value={studentSearchQuery}
                      onChange={(e) => setStudentSearchQuery(e.target.value)}
                      placeholder="Search by name or email..."
                      className={inputClassName + " pl-10"}
                    />
                  </div>
                </div>
                <div className="border border-gray-200 rounded-xl max-h-[280px] overflow-y-auto custom-scrollbar">
                  {filteredStudents.length === 0 ? (
                    <div className="p-4 text-center text-gray-500 text-sm">
                      {studentSearchQuery
                        ? "No students match your search"
                        : "No students available"}
                    </div>
                  ) : (
                    <table className="w-full">
                      <thead className="bg-gray-50 sticky top-0">
                        <tr>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Select
                          </th>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Name
                          </th>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Email
                          </th>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Risk
                          </th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-100">
                        {filteredStudents.map((student) => (
                          <tr
                            key={student.id}
                            className={`transition-colors cursor-pointer ${
                              selectedStudents.includes(student.id)
                                ? "bg-brand-600/5 hover:bg-brand-600/10"
                                : "hover:bg-gray-50"
                            }`}
                            onClick={() => toggleStudentSelection(student.id)}
                          >
                            <td className="py-2.5 px-4" onClick={(e) => e.stopPropagation()}>
                              <input
                                type="checkbox"
                                checked={selectedStudents.includes(student.id)}
                                onChange={() => toggleStudentSelection(student.id)}
                                className="w-4 h-4 text-brand-600 rounded focus:ring-brand-600"
                              />
                            </td>
                            <td className="py-2.5 px-4 text-sm text-gray-800">
                              <div className="flex items-center gap-2">
                                <Avatar
                                  name={student.name}
                                  src={student.picture_url}
                                  userId={student.id}
                                  sex={student.sex}
                                  size="xs"
                                />
                                {student.name}
                              </div>
                            </td>
                            <td className="py-2.5 px-4 text-sm text-gray-500">{student.email}</td>
                            <td className="py-2.5 px-4">
                              <span
                                className={`px-2 py-0.5 text-xs font-bold rounded-full ${
                                  student.risk_level === "at_risk"
                                    ? "bg-red-100 text-red-700"
                                    : student.risk_level === "safe"
                                      ? "bg-emerald-100 text-emerald-700"
                                      : "bg-gray-100 text-gray-700"
                                }`}
                              >
                                {student.risk_level === "at_risk"
                                  ? "Low performing"
                                  : student.risk_level === "safe"
                                    ? "On track"
                                    : "Not scored yet"}
                              </span>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </div>
                <p className="text-sm text-gray-500 mt-2">{assignCount} student(s) selected</p>
              </div>
            </div>

            <div className="p-4 border-t border-hairline bg-subtle">
              <div className="flex justify-end gap-3">
                <button
                  onClick={() => setShowAssignModal(false)}
                  className="px-5 py-2.5 bg-surface border border-gray-200 hover:bg-gray-50 rounded-lg text-sm font-medium text-gray-700 transition-all"
                >
                  Cancel
                </button>
                <button
                  onClick={handleAssignScenario}
                  disabled={assignCount === 0 || !assignDeadline || assigning}
                  className="px-5 py-2.5 bg-brand-600 text-white rounded-lg font-medium hover:bg-brand-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 shadow-[0_2px_6px_rgba(27,107,123,0.2)]"
                >
                  {assigning && <EcgLoader />}
                  Assign to {assignCount} Student
                  {assignCount !== 1 ? "s" : ""}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Link Patient Modal */}
      {showLinkPatientModal && linkPatientTarget && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-surface rounded-xl w-full max-w-3xl max-h-[85vh] overflow-hidden flex flex-col shadow-[0_8px_30px_rgba(0,0,0,0.12)] border border-hairline">
            <div className="p-4 border-b border-hairline flex items-center justify-between bg-subtle">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-brand-600/10 rounded-lg flex items-center justify-center">
                  <FontAwesomeIcon icon={faHospitalUser} className="text-brand-600 w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-gray-900">
                    {linkPatientTarget.patient_id ? "Switch Patient" : "Link Patient"}
                  </h3>
                  <p className="text-sm text-gray-500 line-clamp-1">{linkPatientTarget.title}</p>
                </div>
              </div>
              <button
                onClick={closeLinkPatientModal}
                className="p-2 hover:bg-gray-200 rounded-lg transition-colors"
              >
                <FontAwesomeIcon icon={faTimes} className="w-5 h-5 text-gray-500" />
              </button>
            </div>

            <div className="p-4 space-y-3 overflow-y-auto flex-1">
              <p className="text-sm text-gray-500">
                Every patient case needs a patient so students can chart vitals and EHR data for the
                case — pick one below.
              </p>

              {linkPatientSelected && (
                <div className="p-3 bg-teal-50 border border-teal-200 rounded-xl flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 bg-teal-100 rounded-full flex items-center justify-center text-teal-700">
                      <FontAwesomeIcon icon={faHospitalUser} className="w-4 h-4" />
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-gray-800">
                        {linkPatientSelected.name}
                      </p>
                      <p className="text-xs text-gray-500">
                        {linkPatientSelected.diagnosis} · {linkPatientSelected.mimic_id}
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={() => setLinkPatientId("")}
                    className="text-xs text-teal-700 hover:text-teal-800 font-medium"
                  >
                    Clear
                  </button>
                </div>
              )}

              <div className="border border-gray-200 rounded-xl overflow-hidden">
                <div className="p-3 border-b border-gray-200 bg-subtle">
                  <div className="relative">
                    <FontAwesomeIcon
                      icon={faSearch}
                      className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500"
                    />
                    <input
                      type="text"
                      value={linkPatientSearchQuery}
                      onChange={(e) => setLinkPatientSearchQuery(e.target.value)}
                      placeholder="Search patients by name, diagnosis, MIMIC ID, or room..."
                      className={inputClassName + " pl-10"}
                    />
                  </div>
                </div>
                <div className="max-h-[260px] overflow-y-auto custom-scrollbar">
                  {loadingPatients ? (
                    <div className="p-8 text-center">
                      <EcgLoader size="md" className="text-brand-600" />
                      <p className="text-sm text-gray-500 mt-2">Loading patients...</p>
                    </div>
                  ) : linkModalFilteredPatients.length === 0 ? (
                    <div className="p-6 text-center text-gray-500 text-sm">
                      {linkPatientSearchQuery
                        ? "No patients match your search."
                        : "No MIMIC-IV patients available."}
                    </div>
                  ) : (
                    <table className="w-full">
                      <thead className="bg-gray-50 sticky top-0">
                        <tr>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Patient
                          </th>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Diagnosis
                          </th>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Room
                          </th>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            MIMIC ID
                          </th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-100">
                        {linkModalFilteredPatients.map((patient) => (
                          <tr
                            key={patient.id}
                            onClick={() => setLinkPatientId(patient.id)}
                            className={`cursor-pointer transition-colors ${
                              linkPatientId === patient.id
                                ? "bg-brand-600/5 hover:bg-brand-600/10"
                                : "hover:bg-gray-50"
                            }`}
                          >
                            <td className="py-2.5 px-4">
                              <div className="flex items-center gap-2">
                                <div className="w-7 h-7 bg-brand-600/10 rounded-full flex items-center justify-center text-brand-600 text-xs font-semibold">
                                  {patient.name.charAt(0)}
                                </div>
                                <div>
                                  <p className="text-sm font-medium text-gray-800">
                                    {patient.name}
                                  </p>
                                  <p className="text-xs text-gray-500">
                                    {patient.age}yo {patient.gender}
                                  </p>
                                </div>
                              </div>
                            </td>
                            <td className="py-2.5 px-4 text-sm text-gray-600">
                              {patient.diagnosis}
                            </td>
                            <td className="py-2.5 px-4 text-sm text-gray-600">
                              {patient.room_number}
                            </td>
                            <td className="py-2.5 px-4">
                              <span className="text-xs font-mono text-gray-500">
                                {patient.mimic_id}
                              </span>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </div>
              </div>
            </div>

            <div className="p-4 border-t border-hairline bg-subtle flex justify-end gap-3">
              <button
                onClick={closeLinkPatientModal}
                className="px-5 py-2.5 bg-surface border border-gray-200 hover:bg-gray-50 rounded-lg text-sm font-medium text-gray-700 transition-all"
              >
                Cancel
              </button>
              <button
                onClick={handleSavePatientLink}
                disabled={savingPatientLink || !linkPatientId}
                className="px-5 py-2.5 bg-brand-600 text-white rounded-lg font-medium hover:bg-brand-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 shadow-[0_2px_6px_rgba(27,107,123,0.2)]"
              >
                {savingPatientLink && <EcgLoader />}
                Save
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
