"use client";

import { useState, useEffect, useMemo, useCallback, useRef } from "react";
import { useRouter } from "next/navigation";
import { createPortal } from "react-dom";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faRobot,
  faPlus,
  faSearch,
  faFilter,
  faTimes,
  faSpinner,
  faEye,
  faUserPlus,
  faBookOpen,
  faListCheck,
  faHeartbeat,
  faStethoscope,
  faCalendarDay,
  faGraduationCap,
  faHospitalUser,
  faNotesMedical,
  faExclamationTriangle,
  faUsers,
  faCheck,
  faUser,
  faChevronDown,
  faLayerGroup,
  faPenToSquare,
  faTrash,
  faTriangleExclamation,
} from "@fortawesome/free-solid-svg-icons";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  fetchFacultyScenarios,
  createScenario,
  updateScenario,
  deleteScenario,
  generateScenarioBatch,
  ScenarioDraft,
  SimulationScenario,
  fetchFacultyStudents,
  FacultyStudent,
  assignScenarioToStudents,
  logAuditAction,
  getCurrentFacultyUser,
  fetchFacultyPatients,
  assignPatientRooms,
  FacultyPatient,
} from "../../lib/api";
import { SkeletonInlineStatCard, SkeletonScenarioCard } from "../../components/skeletons";
import PageHeader from "../../components/PageHeader";
import StatTile from "../../components/StatTile";
import Card from "../../components/Card";
import Avatar from "../../components/Avatar";


const SCENARIO_CATEGORIES = [
  "Cardiac Emergency",
  "Respiratory Emergency",
  "Neurological Emergency",
  "Trauma",
  "Medical-Surgical",
  "Patient Education",
  "Infection Management",
  "Critical Care",
  "Medication Safety",
  "General",
] as const;

const emptyEditForm = {
  title: "",
  description: "",
  difficulty: "intermediate" as "beginner" | "intermediate" | "advanced",
  category: "General",
  learningObjectives: "",
  patientId: "",
};

const inputClassName =
  "w-full px-4 py-3 bg-surface border border-gray-400 rounded-xl text-gray-900 placeholder:text-gray-600 focus:outline-none focus:ring-2 focus:ring-brand-600/30 focus:border-brand-600 focus:bg-surface transition-all text-sm shadow-sm";

/** The batch route caps a single request at 12 (sequential, rate-limited AI
 *  generation, inside a 60s serverless timeout). Larger counts are generated by
 *  looping the route in sub-batches of this size — no fixed total ceiling. */
const MAX_PER_REQUEST = 12;

const labelClassName = "block text-sm font-bold text-gray-800 mb-2";

type MenuAction = {
  label: string;
  icon: IconDefinition;
  onClick: () => void;
  /** Destructive items read red and sit below a divider. */
  danger?: boolean;
};

/**
 * The per-card actions, collapsed behind one trigger. The menu renders in a
 * portal because the card clips to its rounded corners (overflow-hidden), so an
 * in-flow dropdown would be cut off; it is positioned from the trigger's rect
 * and flips above when there is no room below. Scroll or resize closes it
 * rather than chasing the trigger with a fixed element.
 */
function ActionsMenu({ actions }: { actions: MenuAction[] }) {
  const [open, setOpen] = useState(false);
  const [coords, setCoords] = useState<{ top: number; left: number; flip: boolean } | null>(null);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);

  const place = useCallback(() => {
    const el = triggerRef.current;
    if (!el) return;
    const r = el.getBoundingClientRect();
    const menuHeight = 44 * actions.length + 8;
    const flip = r.bottom + 6 + menuHeight > window.innerHeight && r.top - menuHeight > 0;
    setCoords({ top: flip ? r.top - 6 : r.bottom + 6, left: r.right, flip });
  }, [actions.length]);

  useEffect(() => {
    if (!open) return;
    place();
    const close = () => setOpen(false);
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    const onDown = (e: MouseEvent) => {
      const t = e.target as Node;
      if (triggerRef.current?.contains(t) || menuRef.current?.contains(t)) return;
      setOpen(false);
    };
    window.addEventListener("scroll", close, true);
    window.addEventListener("resize", close);
    document.addEventListener("keydown", onKey);
    document.addEventListener("mousedown", onDown);
    return () => {
      window.removeEventListener("scroll", close, true);
      window.removeEventListener("resize", close);
      document.removeEventListener("keydown", onKey);
      document.removeEventListener("mousedown", onDown);
    };
  }, [open, place]);

  return (
    <>
      <button
        ref={triggerRef}
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-haspopup="menu"
        aria-expanded={open}
        className="flex w-full items-center justify-center gap-2 rounded-lg border border-brand-600/20 py-2 text-sm font-medium text-brand-600 transition-colors hover:border-brand-600/40 hover:bg-brand-600/5"
      >
        Actions
        <FontAwesomeIcon
          icon={faChevronDown}
          className={`w-3 h-3 transition-transform ${open ? "rotate-180" : ""}`}
        />
      </button>

      {open &&
        coords &&
        createPortal(
          <div
            ref={menuRef}
            role="menu"
            style={{
              position: "fixed",
              top: coords.top,
              left: coords.left,
              transform: coords.flip ? "translate(-100%, -100%)" : "translateX(-100%)",
            }}
            className="z-50 min-w-44 overflow-hidden rounded-xl border border-hairline bg-surface py-1 shadow-[0_8px_30px_rgba(0,0,0,0.12)]"
          >
            {actions.map((action) => (
              <button
                key={action.label}
                type="button"
                role="menuitem"
                onClick={() => {
                  setOpen(false);
                  action.onClick();
                }}
                className={`group flex w-full items-center gap-2.5 px-3.5 py-2.5 text-left text-sm transition-colors ${
                  action.danger
                    ? "border-t border-hairline text-rose-600 hover:bg-rose-50"
                    : "text-gray-700 hover:bg-brand-600/5 hover:text-brand-700"
                }`}
              >
                <FontAwesomeIcon
                  icon={action.icon}
                  className={`w-4 h-4 transition-colors ${
                    action.danger ? "text-rose-500" : "text-gray-400 group-hover:text-brand-600"
                  }`}
                />
                {action.label}
              </button>
            ))}
          </div>,
          document.body,
        )}
    </>
  );
}

export default function FacultyScenariosClient() {
  const router = useRouter();
  const [scenarios, setScenarios] = useState<SimulationScenario[]>([]);
  const [loading, setLoading] = useState(true);

  const [searchQuery, setSearchQuery] = useState("");
  const [difficultyFilter, setDifficultyFilter] = useState("all");
  const [categoryFilter, setCategoryFilter] = useState("all");

  const [patients, setPatients] = useState<FacultyPatient[]>([]);
  const [loadingPatients, setLoadingPatients] = useState(false);

  const [showBatchModal, setShowBatchModal] = useState(false);
  // The committed numeric count that generation uses, plus the raw field text so
  // it can be cleared and retyped freely without snapping back mid-edit.
  const [batchCount, setBatchCount] = useState(6);
  const [batchCountInput, setBatchCountInput] = useState("6");
  const [batchCategories, setBatchCategories] = useState<string[]>([]);
  const [batchDifficulty, setBatchDifficulty] = useState("");
  const [batchTopic, setBatchTopic] = useState("");
  const [batchUsePatients, setBatchUsePatients] = useState(true);
  // How the library's grounded patients are placed into rooms on save.
  const [batchRoomMode, setBatchRoomMode] = useState<"fill" | "spread">("fill");
  const [batchDrafts, setBatchDrafts] = useState<ScenarioDraft[] | null>(null);
  const [batchSelected, setBatchSelected] = useState<number[]>([]);
  const [batchGenerating, setBatchGenerating] = useState(false);
  const [batchProgress, setBatchProgress] = useState(0);
  const [batchCancelling, setBatchCancelling] = useState(false);
  // Refs, not state: the running generate loop reads these synchronously and a
  // state update wouldn't reach its closure in time to stop the next sub-batch.
  const batchCancelRef = useRef(false);
  const batchAbortRef = useRef<AbortController | null>(null);
  const [batchSaving, setBatchSaving] = useState(false);
  const [batchSavedCount, setBatchSavedCount] = useState(0);
  const [batchError, setBatchError] = useState<string | null>(null);
  const [batchWarning, setBatchWarning] = useState<string | null>(null);

  const [showEditModal, setShowEditModal] = useState(false);
  const [editTarget, setEditTarget] = useState<SimulationScenario | null>(null);
  const [editForm, setEditForm] = useState(emptyEditForm);
  const [saving, setSaving] = useState(false);

  const [showDetailsModal, setShowDetailsModal] = useState(false);
  const [selectedScenario, setSelectedScenario] = useState<SimulationScenario | null>(null);

  const [showAssignModal, setShowAssignModal] = useState(false);
  const [students, setStudents] = useState<FacultyStudent[]>([]);
  const [selectedStudents, setSelectedStudents] = useState<string[]>([]);
  const [assignDeadline, setAssignDeadline] = useState("");
  const [assignRequired, setAssignRequired] = useState(false);
  const [studentSearchQuery, setStudentSearchQuery] = useState("");
  const [assigning, setAssigning] = useState(false);

  const [showLinkPatientModal, setShowLinkPatientModal] = useState(false);
  const [linkPatientTarget, setLinkPatientTarget] = useState<SimulationScenario | null>(null);
  const [linkPatientId, setLinkPatientId] = useState("");
  const [linkPatientSearchQuery, setLinkPatientSearchQuery] = useState("");
  const [savingPatientLink, setSavingPatientLink] = useState(false);


  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<SimulationScenario | null>(null);
  const [deleting, setDeleting] = useState(false);
  const [deleteError, setDeleteError] = useState<string | null>(null);

  const loadStudents = useCallback(async () => {
    const data = await fetchFacultyStudents();
    setStudents(data);
  }, []);

  const loadScenarios = useCallback(async () => {
    setLoading(true);
    const data = await fetchFacultyScenarios();
    setScenarios(data);
    setLoading(false);
  }, []);

  useEffect(() => {
    let mounted = true;
    async function init() {
      await loadScenarios();
      if (mounted) await loadStudents();
    }
    void init();
    return () => {
      mounted = false;
    };
  }, [loadScenarios, loadStudents]);

  const loadPatientsForSelector = async () => {
    setLoadingPatients(true);
    const data = await fetchFacultyPatients();
    setPatients(data);
    setLoadingPatients(false);
  };

  const categories = useMemo(
    () => Array.from(new Set(scenarios.map((s) => s.category).filter(Boolean))),
    [scenarios],
  );

  const filteredScenarios = useMemo(() => {
    return scenarios.filter((scenario) => {
      const matchesSearch =
        scenario.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        scenario.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
        scenario.category.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesDifficulty =
        difficultyFilter === "all" || scenario.difficulty === difficultyFilter;
      const matchesCategory = categoryFilter === "all" || scenario.category === categoryFilter;
      return matchesSearch && matchesDifficulty && matchesCategory;
    });
  }, [scenarios, searchQuery, difficultyFilter, categoryFilter]);


  const linkModalFilteredPatients = useMemo(() => {
    const q = linkPatientSearchQuery.toLowerCase();
    return patients.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        p.diagnosis.toLowerCase().includes(q) ||
        (p.mimic_id || "").toLowerCase().includes(q) ||
        p.room_number.toLowerCase().includes(q),
    );
  }, [patients, linkPatientSearchQuery]);

  const linkPatientSelected = useMemo(
    () => patients.find((p) => p.id === linkPatientId) || null,
    [patients, linkPatientId],
  );

  const openBatchModal = () => {
    setBatchDrafts(null);
    setBatchSelected([]);
    setBatchError(null);
    setBatchWarning(null);
    setBatchSavedCount(0);
    setBatchProgress(0);
    setBatchCancelling(false);
    setShowBatchModal(true);
    if (patients.length === 0) void loadPatientsForSelector();
  };

  const closeBatchModal = () => {
    if (batchGenerating || batchSaving) return;
    setShowBatchModal(false);
    setBatchDrafts(null);
    setBatchSelected([]);
    setBatchError(null);
    setBatchWarning(null);
    setBatchSavedCount(0);
    setBatchProgress(0);
    setBatchCancelling(false);
  };

  const toggleBatchCategory = (category: string) => {
    setBatchCategories((prev) =>
      prev.includes(category) ? prev.filter((c) => c !== category) : [...prev, category],
    );
  };

  /** Stops the generate loop and aborts the request in flight, keeping whatever
   *  sub-batches already came back. */
  const cancelBatch = () => {
    batchCancelRef.current = true;
    batchAbortRef.current?.abort();
    setBatchCancelling(true);
  };

  const handleGenerateBatch = async () => {
    batchCancelRef.current = false;
    setBatchCancelling(false);
    setBatchGenerating(true);
    setBatchError(null);
    setBatchWarning(null);
    setBatchDrafts(null);
    setBatchProgress(0);

    const total = Math.max(1, batchCount);
    const collected: ScenarioDraft[] = [];
    const warnings: string[] = [];

    // A single request tops out at the server's per-batch cap (60s serverless
    // limit), so a larger library is several sequential requests. Each carries
    // the titles produced so far as avoid_titles, so sub-batches don't collide.
    for (let remaining = total; remaining > 0; remaining -= MAX_PER_REQUEST) {
      if (batchCancelRef.current) break;
      const chunkCount = Math.min(MAX_PER_REQUEST, remaining);
      const controller = new AbortController();
      batchAbortRef.current = controller;
      const result = await generateScenarioBatch(
        {
          count: chunkCount,
          categories: batchCategories,
          difficulty: batchDifficulty || undefined,
          topic: batchTopic.trim() || undefined,
          usePatients: batchUsePatients,
          avoidTitles: collected.map((s) => s.title),
        },
        controller.signal,
      );

      // A cancel lands here as an aborted-fetch error; treat it as a clean stop.
      if (batchCancelRef.current) break;

      if ("error" in result) {
        // A first-request failure is fatal; a later one keeps what we have.
        if (collected.length === 0) {
          setBatchError(result.error);
          setBatchGenerating(false);
          return;
        }
        warnings.push(result.error);
        break;
      }

      collected.push(...result.scenarios);
      if (result.warning) warnings.push(result.warning);
      setBatchProgress(collected.length);

      // The model can return fewer than asked; stop rather than loop chasing the rest.
      if (result.scenarios.length < chunkCount) break;
    }

    batchAbortRef.current = null;
    const cancelled = batchCancelRef.current;
    setBatchCancelling(false);

    if (collected.length === 0) {
      // A cancel with nothing in hand just returns to the form, no error.
      if (!cancelled) {
        setBatchError("The AI service didn't return any scenarios. Please try again.");
      }
      setBatchGenerating(false);
      return;
    }

    setBatchDrafts(collected);
    setBatchSelected(collected.map((_, i) => i));
    setBatchWarning(
      cancelled
        ? `Stopped at ${collected.length} scenario${collected.length === 1 ? "" : "s"}. Keep these or generate more.`
        : collected.length < total
          ? `Generated ${collected.length} of ${total} — the AI service fell short. Keep these or try again for more.`
          : (warnings[0] ?? null),
    );
    setBatchGenerating(false);
  };

  const handleSaveBatch = async () => {
    if (!batchDrafts || batchSelected.length === 0) return;

    setBatchSaving(true);
    setBatchSavedCount(0);

    const chosen = batchSelected
      .slice()
      .sort((a, b) => a - b)
      .map((i) => batchDrafts[i]);

    let saved = 0;
    const savedPatientIds: string[] = [];
    for (const draft of chosen) {
      const created = await createScenario({
        title: draft.title,
        description: draft.description,
        difficulty: draft.difficulty,
        category: draft.category,
        patient_case: draft.patient_case,
        patient_id: draft.patient_id,
        learning_objectives: draft.learning_objectives,
        is_ai_generated: true,
      });
      if (created) {
        saved++;
        setBatchSavedCount(saved);
        if (draft.patient_id) savedPatientIds.push(draft.patient_id);
      }
    }

    // Auto-place the grounded patients into rooms (capacity-aware) per the chosen mode.
    if (savedPatientIds.length > 0) {
      await assignPatientRooms([...new Set(savedPatientIds)], batchRoomMode);
    }

    if (saved > 0) {
      await loadScenarios();
      const faculty = getCurrentFacultyUser();
      if (faculty) {
        logAuditAction({
          faculty_id: faculty.id,
          faculty_name: faculty.name,
          tab: "scenarios",
          action: "ai_generate_scenario_library",
          details: `AI generated and saved ${saved} scenario${saved === 1 ? "" : "s"}`,
          target_type: "scenario",
          target_id: "",
          metadata: { count: saved, requested: batchCount, topic: batchTopic.trim() || null },
        });
      }
    }

    setBatchSaving(false);
    setShowBatchModal(false);
    setBatchDrafts(null);
    setBatchSelected([]);
  };

  const handleOpenEditModal = (scenario: SimulationScenario) => {
    setEditTarget(scenario);
    setEditForm({
      title: scenario.title,
      description: scenario.description,
      difficulty: scenario.difficulty as typeof emptyEditForm.difficulty,
      category: scenario.category,
      learningObjectives: (scenario.learning_objectives ?? []).join("\n"),
      patientId: scenario.patient_id ?? "",
    });
    setShowEditModal(true);
    if (patients.length === 0) void loadPatientsForSelector();
  };

  const closeEditModal = () => {
    setShowEditModal(false);
    setEditTarget(null);
    setEditForm(emptyEditForm);
  };

  const handleSaveEdit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editTarget || !editForm.title.trim()) return;

    setSaving(true);
    const updated = await updateScenario(editTarget.id, {
      title: editForm.title,
      description: editForm.description,
      difficulty: editForm.difficulty,
      category: editForm.category || "General",
      patient_id: editForm.patientId || null,
      learning_objectives: editForm.learningObjectives
        .split("\n")
        .map((o) => o.trim())
        .filter(Boolean),
    });

    if (updated) {
      await loadScenarios();
      const faculty = getCurrentFacultyUser();
      if (faculty) {
        logAuditAction({
          faculty_id: faculty.id,
          faculty_name: faculty.name,
          tab: "scenarios",
          action: "update_scenario",
          details: `Updated scenario: ${updated.title}`,
          target_type: "scenario",
          target_id: editTarget.id,
          metadata: { scenario_title: updated.title },
        });
      }
    }

    setSaving(false);
    closeEditModal();
  };

  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty) {
      case "advanced":
        return "bg-rose-100 text-rose-700 border-rose-200";
      case "intermediate":
        return "bg-amber-100 text-amber-700 border-amber-200";
      case "beginner":
        return "bg-emerald-100 text-emerald-700 border-emerald-200";
      default:
        return "bg-gray-100 text-gray-700 border-gray-200";
    }
  };

  const difficultyBar: Record<string, string> = {
    advanced: "bg-rose-500",
    intermediate: "bg-amber-500",
    beginner: "bg-emerald-500",
  };

  const getDifficultyIcon = (difficulty: string) => {
    switch (difficulty) {
      case "advanced":
        return faExclamationTriangle;
      case "beginner":
        return faGraduationCap;
      default:
        return faBookOpen;
    }
  };

  const handleViewDetails = (scenario: SimulationScenario) => {
    setSelectedScenario(scenario);
    setShowDetailsModal(true);
  };

  const handleOpenAssignModal = (scenario: SimulationScenario) => {
    setSelectedScenario(scenario);
    setSelectedStudents([]);
    setAssignDeadline("");
    setAssignRequired(false);
    setStudentSearchQuery("");
    setShowAssignModal(true);
  };

  const toggleStudentSelection = (studentId: string) => {
    setSelectedStudents((prev) =>
      prev.includes(studentId) ? prev.filter((id) => id !== studentId) : [...prev, studentId],
    );
  };

  const handleAssignScenario = async () => {
    if (!selectedScenario || selectedStudents.length === 0 || !assignDeadline) return;

    setAssigning(true);
    const assignments = await assignScenarioToStudents(
      selectedScenario.id,
      selectedStudents,
      assignDeadline,
      assignRequired,
    );

    if (assignments.length > 0) {
      await loadScenarios();
      const faculty = getCurrentFacultyUser();
      if (faculty) {
        logAuditAction({
          faculty_id: faculty.id,
          faculty_name: faculty.name,
          tab: "scenarios",
          action: "assign_scenario",
          details: `Assigned scenario "${selectedScenario.title}" to ${selectedStudents.length} student(s)`,
          target_type: "scenario",
          target_id: selectedScenario.id,
          metadata: {
            scenario_title: selectedScenario.title,
            student_count: selectedStudents.length,
            required: assignRequired,
          },
        });
      }
    }

    setAssigning(false);
    setShowAssignModal(false);
    setSelectedScenario(null);
    setSelectedStudents([]);
    setStudentSearchQuery("");
  };

  const handleOpenLinkPatientModal = (scenario: SimulationScenario) => {
    setLinkPatientTarget(scenario);
    setLinkPatientId(scenario.patient_id || "");
    setLinkPatientSearchQuery("");
    setShowLinkPatientModal(true);
    if (patients.length === 0) void loadPatientsForSelector();
  };

  const closeLinkPatientModal = () => {
    setShowLinkPatientModal(false);
    setLinkPatientTarget(null);
    setLinkPatientId("");
    setLinkPatientSearchQuery("");
  };

  const handleSavePatientLink = async () => {
    if (!linkPatientTarget) return;

    setSavingPatientLink(true);
    const updated = await updateScenario(linkPatientTarget.id, {
      patient_id: linkPatientId || null,
    });

    if (updated) {
      await loadScenarios();
      const faculty = getCurrentFacultyUser();
      if (faculty) {
        logAuditAction({
          faculty_id: faculty.id,
          faculty_name: faculty.name,
          tab: "scenarios",
          action: "link_scenario_patient",
          details: linkPatientId
            ? `Linked scenario "${linkPatientTarget.title}" to a patient`
            : `Unlinked patient from scenario "${linkPatientTarget.title}"`,
          target_type: "scenario",
          target_id: linkPatientTarget.id,
          metadata: { scenario_title: linkPatientTarget.title, patient_id: linkPatientId || null },
        });
      }
    }

    setSavingPatientLink(false);
    closeLinkPatientModal();
  };

  const handleOpenDeleteModal = (scenario: SimulationScenario) => {
    setDeleteTarget(scenario);
    setDeleteError(null);
    setShowDeleteModal(true);
  };

  const closeDeleteModal = () => {
    if (deleting) return;
    setShowDeleteModal(false);
    setDeleteTarget(null);
    setDeleteError(null);
  };

  const handleConfirmDelete = async () => {
    if (!deleteTarget) return;

    setDeleting(true);
    setDeleteError(null);
    const ok = await deleteScenario(deleteTarget.id);

    if (!ok) {
      setDeleteError("Could not delete the scenario. Please try again.");
      setDeleting(false);
      return;
    }

    setScenarios((prev) => prev.filter((s) => s.id !== deleteTarget.id));
    const faculty = getCurrentFacultyUser();
    if (faculty) {
      logAuditAction({
        faculty_id: faculty.id,
        faculty_name: faculty.name,
        tab: "scenarios",
        action: "delete_scenario",
        details: `Deleted scenario: ${deleteTarget.title}`,
        target_type: "scenario",
        target_id: deleteTarget.id,
        metadata: { scenario_title: deleteTarget.title },
      });
    }

    setDeleting(false);
    setShowDeleteModal(false);
    setDeleteTarget(null);
  };

  const filteredStudents = students.filter(
    (student) =>
      student.name.toLowerCase().includes(studentSearchQuery.toLowerCase()) ||
      student.email.toLowerCase().includes(studentSearchQuery.toLowerCase()),
  );

  const selectClassName =
    "w-full px-4 py-3 bg-surface border border-gray-400 rounded-xl text-gray-900 focus:outline-none focus:ring-2 focus:ring-brand-600/30 focus:border-brand-600 focus:bg-surface transition-all text-sm appearance-none shadow-sm cursor-pointer";

  return (
    <div>
      <PageHeader
        badge={{
          icon: <FontAwesomeIcon icon={faNotesMedical} className="w-3.5 h-3.5" />,
          label: "Simulation Scenarios",
        }}
        title="Simulation Scenarios"
        subtitle="Manage clinical simulation scenarios for student training"
      />

      {/* Stats */}
      {loading ? (
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-4">
          {Array.from({ length: 3 }).map((_, i) => (
            <SkeletonInlineStatCard key={i} />
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-4">
          <StatTile
            icon={<FontAwesomeIcon icon={faNotesMedical} className="w-5 h-5" />}
            value={scenarios.length}
            label="Total Scenarios"
            iconBg="bg-brand-600/10"
            iconColor="text-brand-600"
          />
          <StatTile
            icon={<FontAwesomeIcon icon={faRobot} className="w-5 h-5" />}
            value={scenarios.filter((s) => s.is_ai_generated).length}
            label="AI Generated"
            iconBg="bg-brand-50"
            iconColor="text-brand-600"
          />
          <StatTile
            icon={<FontAwesomeIcon icon={faUsers} className="w-5 h-5" />}
            value={scenarios.reduce((sum, s) => sum + s.student_count, 0)}
            label="Students Assigned"
            iconBg="bg-emerald-50"
            iconColor="text-emerald-600"
          />
        </div>
      )}

      {/* Filters */}
      <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4 mb-4">
        <div className="relative w-full lg:w-96">
          <FontAwesomeIcon
            icon={faSearch}
            className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500"
          />
          <input
            type="text"
            placeholder="Search scenarios..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className={inputClassName + " pl-10"}
          />
        </div>
        <div className="flex items-center gap-3 w-full lg:w-auto">
          <div className="relative flex-1 lg:flex-none">
            <FontAwesomeIcon
              icon={faFilter}
              className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500"
            />
            <select
              value={difficultyFilter}
              onChange={(e) => setDifficultyFilter(e.target.value)}
              className={selectClassName + " pl-10 pr-10 w-full lg:w-44"}
            >
              <option value="all">All Difficulties</option>
              <option value="beginner">Beginner</option>
              <option value="intermediate">Intermediate</option>
              <option value="advanced">Advanced</option>
            </select>
            <FontAwesomeIcon
              icon={faChevronDown}
              className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500 pointer-events-none"
            />
          </div>
          <div className="relative flex-1 lg:flex-none">
            <FontAwesomeIcon
              icon={faHospitalUser}
              className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500"
            />
            <select
              value={categoryFilter}
              onChange={(e) => setCategoryFilter(e.target.value)}
              className={selectClassName + " pl-10 pr-10 w-full lg:w-48"}
            >
              <option value="all">All Categories</option>
              {categories.map((cat) => (
                <option key={cat} value={cat}>
                  {cat}
                </option>
              ))}
            </select>
            <FontAwesomeIcon
              icon={faChevronDown}
              className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500 pointer-events-none"
            />
          </div>
          <div className="flex justify-end gap-3">
            {/* One entry: the manual form with an AI-generate assist inside it. */}
            <button
              onClick={() => router.push("/faculty/scenarios/new")}
              className="flex shrink-0 items-center gap-2 whitespace-nowrap rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white shadow-[0_2px_8px_-1px_rgb(27_107_123_/_0.35)] transition-all hover:bg-brand-700 hover:shadow-[0_4px_14px_-2px_rgb(27_107_123_/_0.45)]"
            >
              <FontAwesomeIcon icon={faPlus} className="w-4 h-4" />
              Create Scenario
            </button>
            <button
              onClick={openBatchModal}
              className="group flex shrink-0 items-center gap-2 whitespace-nowrap rounded-xl border border-brand-700/25 bg-surface px-4 py-2.5 text-sm font-semibold text-brand-800 transition-all hover:border-brand-700/40 hover:bg-brand-50"
            >
              <FontAwesomeIcon
                icon={faLayerGroup}
                className="w-4 h-4 text-brand-600 transition-transform group-hover:scale-110"
              />
              Generate Library
            </button>
            <button
              onClick={() => router.push("/faculty/scenarios/link")}
              className="group flex shrink-0 items-center gap-2 whitespace-nowrap rounded-xl border border-gray-300 bg-surface px-4 py-2.5 text-sm font-semibold text-gray-700 transition-all hover:border-brand-300 hover:bg-brand-50"
            >
              <FontAwesomeIcon
                icon={faHospitalUser}
                className="w-4 h-4 text-brand-600 transition-transform group-hover:scale-110"
              />
              Link patients
            </button>
          </div>
        </div>
      </div>

      {/* Scenarios Grid */}
      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {Array.from({ length: 6 }).map((_, i) => (
            <SkeletonScenarioCard key={i} />
          ))}
        </div>
      ) : filteredScenarios.length === 0 ? (
        <div className="bg-surface rounded-xl border border-hairline shadow-[0_1px_3px_0_rgba(0,0,0,0.04),0_1px_2px_-1px_rgba(0,0,0,0.06)] p-12 text-center">
          <FontAwesomeIcon icon={faNotesMedical} className="w-12 h-12 text-gray-300 mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-gray-700">No scenarios found</h3>
          <p className="text-gray-500 text-sm mt-1">
            {searchQuery || difficultyFilter !== "all" || categoryFilter !== "all"
              ? "Try adjusting your filters."
              : "Generate a starter library, or create your first scenario by hand."}
          </p>
          {!searchQuery && difficultyFilter === "all" && categoryFilter === "all" && (
            <button
              onClick={openBatchModal}
              className="mt-4 inline-flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-brand-600 to-brand-800 text-white font-medium rounded-xl hover:from-brand-700 hover:to-brand-900 transition-all shadow-lg shadow-[0_4px_14px_-2px_rgb(27_107_123_/_0.45)]"
            >
              <FontAwesomeIcon icon={faLayerGroup} className="w-4 h-4" />
              Generate Library
            </button>
          )}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredScenarios.map((scenario) => (
            <div
              key={scenario.id}
              className="group relative bg-surface rounded-xl border border-hairline shadow-[0_1px_3px_0_rgba(0,0,0,0.04),0_1px_2px_-1px_rgba(0,0,0,0.06)] hover:shadow-[0_4px_12px_0_rgba(0,0,0,0.06),0_2px_4px_-2px_rgba(0,0,0,0.06)] hover:border-gray-200 transition-all duration-200 overflow-hidden flex flex-col"
            >
              <span
                className={`absolute left-0 top-0 h-full w-0.5 ${difficultyBar[scenario.difficulty] ?? "bg-gray-500"}`}
                aria-hidden
              />
              <div className="p-3 border-b border-hairline flex-1">
                <div className="flex items-start justify-between mb-3">
                  <h3 className="font-semibold text-gray-900 line-clamp-2 pr-2">
                    {scenario.title}
                  </h3>
                  {scenario.is_ai_generated && (
                    <span className="px-2 py-1 bg-brand-100 text-brand-700 text-xs font-medium rounded-full flex items-center gap-1 whitespace-nowrap">
                      <FontAwesomeIcon icon={faRobot} className="w-3 h-3" />
                      AI
                    </span>
                  )}
                </div>
                <p className="text-sm text-gray-500 line-clamp-2 mb-4">{scenario.description}</p>
                <div className="flex items-center gap-2 flex-wrap">
                  <span
                    className={`px-2.5 py-1 rounded-full text-xs font-medium border flex items-center gap-1 ${getDifficultyColor(
                      scenario.difficulty,
                    )}`}
                  >
                    <FontAwesomeIcon
                      icon={getDifficultyIcon(scenario.difficulty)}
                      className="w-3 h-3"
                    />
                    {scenario.difficulty}
                  </span>
                  <span className="px-2.5 py-1 bg-gray-100 text-gray-700 text-xs font-medium rounded-full">
                    {scenario.category}
                  </span>
                  {scenario.patient_name && (
                    <span className="px-2.5 py-1 bg-teal-50 text-teal-700 text-xs font-medium rounded-full flex items-center gap-1">
                      <FontAwesomeIcon icon={faUsers} className="w-3 h-3" />
                      {scenario.patient_name}
                    </span>
                  )}
                </div>
              </div>
              <div className="p-5 bg-subtle">
                <div className="flex items-center justify-between text-sm mb-4">
                  <span className="text-gray-500 flex items-center gap-1.5">
                    <FontAwesomeIcon icon={faUsers} className="w-3.5 h-3.5" />
                    {scenario.student_count} students
                  </span>
                  <span className="text-gray-400 flex items-center gap-1.5">
                    <FontAwesomeIcon icon={faCalendarDay} className="w-3.5 h-3.5" />
                    {new Date(scenario.created_at).toLocaleDateString()}
                  </span>
                </div>
                <ActionsMenu
                  actions={[
                    { label: "View", icon: faEye, onClick: () => handleViewDetails(scenario) },
                    {
                      label: "Edit",
                      icon: faPenToSquare,
                      onClick: () => handleOpenEditModal(scenario),
                    },
                    {
                      label: "Assign",
                      icon: faUserPlus,
                      onClick: () => handleOpenAssignModal(scenario),
                    },
                    {
                      label: scenario.patient_name ? "Change patient" : "Link patient",
                      icon: faHospitalUser,
                      onClick: () => handleOpenLinkPatientModal(scenario),
                    },
                    {
                      label: "Delete",
                      icon: faTrash,
                      danger: true,
                      onClick: () => handleOpenDeleteModal(scenario),
                    },
                  ]}
                />
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Delete Scenario Modal */}
      {showDeleteModal && deleteTarget && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-surface rounded-xl w-full max-w-md overflow-hidden shadow-[0_8px_30px_rgba(0,0,0,0.12)] border border-hairline">
            <div className="p-5">
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 rounded-lg bg-rose-50 flex items-center justify-center shrink-0">
                  <FontAwesomeIcon icon={faTrash} className="w-5 h-5 text-rose-600" />
                </div>
                <div className="min-w-0">
                  <h3 className="text-lg font-bold text-gray-900">Delete scenario?</h3>
                  <p className="text-sm text-gray-500 mt-1">
                    <span className="font-medium text-gray-700">{deleteTarget.title}</span> will be
                    permanently removed. This can&apos;t be undone.
                  </p>
                  {deleteTarget.student_count > 0 && (
                    <div className="mt-3 flex items-start gap-2 rounded-lg border border-amber-200 bg-amber-50 p-2.5 text-xs text-amber-800">
                      <FontAwesomeIcon
                        icon={faTriangleExclamation}
                        className="w-3.5 h-3.5 mt-0.5 shrink-0"
                      />
                      <span>
                        {`Assigned to ${deleteTarget.student_count} student${
                          deleteTarget.student_count === 1 ? "" : "s"
                        }. Their assignments will be removed too.`}
                      </span>
                    </div>
                  )}
                  {deleteError && (
                    <div className="mt-3 p-2.5 rounded-lg bg-red-50 text-red-700 text-xs border border-red-200">
                      {deleteError}
                    </div>
                  )}
                </div>
              </div>
              <div className="flex justify-end gap-3 mt-5">
                <button
                  type="button"
                  onClick={closeDeleteModal}
                  disabled={deleting}
                  className="px-5 py-2.5 bg-surface border border-gray-200 hover:bg-gray-50 rounded-lg text-sm font-medium text-gray-700 transition-all disabled:opacity-50"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleConfirmDelete}
                  disabled={deleting}
                  className="px-5 py-2.5 bg-rose-600 text-white rounded-lg font-medium hover:bg-rose-700 transition-all disabled:opacity-50 flex items-center gap-2 shadow-[0_2px_6px_rgba(225,29,72,0.25)]"
                >
                  {deleting ? (
                    <FontAwesomeIcon icon={faSpinner} spin className="w-4 h-4" />
                  ) : (
                    <FontAwesomeIcon icon={faTrash} className="w-4 h-4" />
                  )}
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Edit Scenario Modal */}
      {showEditModal && editTarget && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-surface rounded-xl w-full max-w-lg max-h-[85vh] overflow-hidden flex flex-col shadow-[0_8px_30px_rgba(0,0,0,0.12)] border border-hairline">
            <div className="p-4 border-b border-hairline flex items-center justify-between bg-subtle">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-brand-600/10 rounded-lg flex items-center justify-center">
                  <FontAwesomeIcon icon={faPenToSquare} className="text-brand-600 w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-gray-900">Edit Scenario</h3>
                  <p className="text-sm text-gray-500 line-clamp-1">{editTarget.title}</p>
                </div>
              </div>
              <button
                onClick={closeEditModal}
                className="p-2 hover:bg-gray-200 rounded-lg transition-colors"
              >
                <FontAwesomeIcon icon={faTimes} className="w-5 h-5 text-gray-500" />
              </button>
            </div>
            <form onSubmit={handleSaveEdit} className="p-4 space-y-3 overflow-y-auto flex-1">
              <div>
                <label className={labelClassName}>Title</label>
                <input
                  required
                  type="text"
                  value={editForm.title}
                  onChange={(e) => setEditForm({ ...editForm, title: e.target.value })}
                  className={inputClassName}
                />
              </div>
              <div>
                <label className={labelClassName}>Description</label>
                <textarea
                  value={editForm.description}
                  onChange={(e) => setEditForm({ ...editForm, description: e.target.value })}
                  rows={3}
                  className={inputClassName + " resize-none"}
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className={labelClassName}>Difficulty</label>
                  <div className="relative">
                    <select
                      value={editForm.difficulty}
                      onChange={(e) =>
                        setEditForm({
                          ...editForm,
                          difficulty: e.target.value as typeof editForm.difficulty,
                        })
                      }
                      className={selectClassName + " pr-10"}
                    >
                      <option value="beginner">Beginner</option>
                      <option value="intermediate">Intermediate</option>
                      <option value="advanced">Advanced</option>
                    </select>
                    <FontAwesomeIcon
                      icon={faChevronDown}
                      className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500 pointer-events-none"
                    />
                  </div>
                </div>
                <div>
                  <label className={labelClassName}>Category</label>
                  <div className="relative">
                    <select
                      value={editForm.category}
                      onChange={(e) => setEditForm({ ...editForm, category: e.target.value })}
                      className={selectClassName + " pr-10"}
                    >
                      {SCENARIO_CATEGORIES.map((cat) => (
                        <option key={cat} value={cat}>
                          {cat}
                        </option>
                      ))}
                    </select>
                    <FontAwesomeIcon
                      icon={faChevronDown}
                      className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500 pointer-events-none"
                    />
                  </div>
                </div>
              </div>
              <div>
                <label className={labelClassName}>Patient</label>
                <div className="relative">
                  <select
                    value={editForm.patientId}
                    onChange={(e) => setEditForm({ ...editForm, patientId: e.target.value })}
                    className={selectClassName + " pr-10"}
                  >
                    <option value="">No linked patient</option>
                    {patients.map((patient) => (
                      <option key={patient.id} value={patient.id}>
                        {patient.name} — {patient.diagnosis}
                        {patient.room_number ? ` (Room ${patient.room_number})` : ""}
                      </option>
                    ))}
                  </select>
                  <FontAwesomeIcon
                    icon={faChevronDown}
                    className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500 pointer-events-none"
                  />
                </div>
              </div>
              <div>
                <label className={labelClassName}>Learning Objectives</label>
                <textarea
                  value={editForm.learningObjectives}
                  onChange={(e) =>
                    setEditForm({ ...editForm, learningObjectives: e.target.value })
                  }
                  rows={4}
                  className={inputClassName + " resize-none"}
                />
                <p className="text-xs text-gray-500 mt-1.5">Enter one objective per line.</p>
              </div>
              <div className="flex justify-end gap-3 pt-2">
                <button
                  type="button"
                  onClick={closeEditModal}
                  className="px-5 py-2.5 bg-surface border border-gray-200 hover:bg-gray-50 rounded-lg text-sm font-medium text-gray-700 transition-all"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={saving || !editForm.title.trim()}
                  className="px-5 py-2.5 bg-brand-600 text-white rounded-lg font-medium hover:bg-brand-700 transition-all disabled:opacity-50 flex items-center gap-2 shadow-[0_2px_6px_rgba(27,107,123,0.2)]"
                >
                  {saving && <FontAwesomeIcon icon={faSpinner} spin className="w-4 h-4" />}
                  Save Changes
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Generate Library Modal */}
      {showBatchModal && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-surface rounded-xl w-full max-w-2xl max-h-[85vh] overflow-hidden flex flex-col shadow-[0_8px_30px_rgba(0,0,0,0.12)] border border-hairline">
            <div className="p-4 border-b border-hairline flex items-center justify-between bg-subtle">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-brand-100 rounded-xl flex items-center justify-center">
                  <FontAwesomeIcon icon={faLayerGroup} className="text-brand-600 w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-gray-900">Generate Scenario Library</h3>
                  <p className="text-sm text-gray-500">
                    Build a spread of cases in one pass, then pick what to keep
                  </p>
                </div>
              </div>
              <button
                onClick={closeBatchModal}
                disabled={batchGenerating || batchSaving}
                className="p-2 hover:bg-gray-200 rounded-lg transition-colors disabled:opacity-40"
              >
                <FontAwesomeIcon icon={faTimes} className="w-5 h-5 text-gray-500" />
              </button>
            </div>

            <div className="p-4 space-y-4 overflow-y-auto flex-1">
              {!batchDrafts ? (
                <>
                  <div>
                    <label className={labelClassName}>How many scenarios?</label>
                    <input
                      type="number"
                      min={1}
                      value={batchCountInput}
                      onChange={(e) => {
                        // Show exactly what's typed (including empty); commit the
                        // count only when it parses to a valid whole number ≥ 1.
                        setBatchCountInput(e.target.value);
                        const n = parseInt(e.target.value, 10);
                        if (!Number.isNaN(n) && n >= 1) setBatchCount(n);
                      }}
                      onBlur={() => setBatchCountInput(String(batchCount))}
                      disabled={batchGenerating}
                      aria-label="Number of scenarios to generate"
                      className={inputClassName}
                    />
                    <p className="text-xs text-gray-500 mt-1.5">
                      {`Enter any number. More than ${MAX_PER_REQUEST} are generated in batches of ${MAX_PER_REQUEST}, so large counts take several minutes.`}
                    </p>
                  </div>

                  <div>
                    <label className={labelClassName}>Categories</label>
                    <div className="flex flex-wrap gap-2">
                      {SCENARIO_CATEGORIES.map((cat) => (
                        <button
                          key={cat}
                          type="button"
                          onClick={() => toggleBatchCategory(cat)}
                          disabled={batchGenerating}
                          className={`px-3 py-1.5 rounded-full text-xs font-medium border transition-all disabled:opacity-50 ${
                            batchCategories.includes(cat)
                              ? "bg-brand-100 text-brand-700 border-brand-300"
                              : "bg-surface text-gray-600 border-gray-300 hover:border-brand-300"
                          }`}
                        >
                          {cat}
                        </button>
                      ))}
                    </div>
                    <p className="text-xs text-gray-500 mt-1.5">
                      {batchCategories.length === 0
                        ? "None selected — the batch will be spread across every category."
                        : `The batch cycles through the ${batchCategories.length} selected categor${batchCategories.length === 1 ? "y" : "ies"}.`}
                    </p>
                  </div>

                  <div>
                    <label className={labelClassName}>Difficulty</label>
                    <div className="relative">
                      <select
                        value={batchDifficulty}
                        onChange={(e) => setBatchDifficulty(e.target.value)}
                        disabled={batchGenerating}
                        className={selectClassName + " pr-10"}
                      >
                        <option value="">Mixed — cycle beginner to advanced</option>
                        <option value="beginner">Beginner only</option>
                        <option value="intermediate">Intermediate only</option>
                        <option value="advanced">Advanced only</option>
                      </select>
                      <FontAwesomeIcon
                        icon={faChevronDown}
                        className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500 pointer-events-none"
                      />
                    </div>
                  </div>

                  <div>
                    <label className={labelClassName}>Teaching focus (optional)</label>
                    <input
                      type="text"
                      value={batchTopic}
                      onChange={(e) => setBatchTopic(e.target.value)}
                      disabled={batchGenerating}
                      placeholder="e.g. post-operative care for second-year students"
                      className={inputClassName}
                    />
                  </div>

                  <label className="flex items-start gap-3 p-3 rounded-xl border border-gray-200 hover:bg-subtle cursor-pointer transition-colors">
                    <input
                      type="checkbox"
                      checked={batchUsePatients}
                      onChange={(e) => setBatchUsePatients(e.target.checked)}
                      disabled={batchGenerating}
                      className="mt-0.5 w-4 h-4 accent-brand-600"
                    />
                    <span>
                      <span className="block text-sm font-semibold text-gray-800">
                        Base each scenario on a real MIMIC patient
                      </span>
                      <span className="block text-xs text-gray-500 mt-0.5">
                        Links every scenario to a patient record so students can chart vitals and
                        EHR data for the case.
                      </span>
                    </span>
                  </label>

                  {batchUsePatients && (
                    <div>
                      <label className={labelClassName}>Room placement</label>
                      <div className="flex gap-2">
                        {(
                          [
                            ["fill", "Fill rooms", "Pack rooms to capacity, one at a time"],
                            ["spread", "Spread evenly", "Balance patients across rooms"],
                          ] as const
                        ).map(([mode, title, hint]) => (
                          <button
                            key={mode}
                            type="button"
                            onClick={() => setBatchRoomMode(mode)}
                            disabled={batchGenerating}
                            className={`flex-1 rounded-xl border px-3 py-2.5 text-left transition-all disabled:opacity-50 ${
                              batchRoomMode === mode
                                ? "border-brand-600 bg-brand-50 ring-1 ring-brand-600/20"
                                : "border-gray-300 bg-surface hover:border-brand-300"
                            }`}
                          >
                            <span className="block text-sm font-semibold text-gray-800">{title}</span>
                            <span className="block text-xs text-gray-500">{hint}</span>
                          </button>
                        ))}
                      </div>
                      <p className="text-xs text-gray-500 mt-1.5">
                        Saved scenarios&apos; patients are placed into rooms without exceeding
                        capacity; any overflow stays unassigned.
                      </p>
                    </div>
                  )}

                  {batchError && (
                    <div className="p-3 rounded-lg text-sm border bg-red-50 text-red-700 border-red-200 flex items-start gap-2">
                      <FontAwesomeIcon
                        icon={faTriangleExclamation}
                        className="w-4 h-4 mt-0.5 shrink-0"
                      />
                      {batchError}
                    </div>
                  )}

                  {batchGenerating && (
                    <div className="p-4 rounded-xl border border-brand-200 bg-brand-50/50 text-sm text-brand-800 flex items-center gap-3">
                      <FontAwesomeIcon icon={faSpinner} spin className="w-4 h-4" />
                      {batchCancelling
                        ? `Stopping — keeping the ${batchProgress} generated so far.`
                        : batchCount > MAX_PER_REQUEST
                          ? `Writing scenarios in batches of ${MAX_PER_REQUEST} — ${batchProgress} of ${batchCount} so far. This can take a few minutes.`
                          : `Writing ${batchCount} scenarios — this takes up to a minute.`}
                    </div>
                  )}
                </>
              ) : (
                <>
                  {batchWarning && (
                    <div className="p-3 rounded-lg text-sm border bg-amber-50 text-amber-700 border-amber-200 flex items-start gap-2">
                      <FontAwesomeIcon
                        icon={faTriangleExclamation}
                        className="w-4 h-4 mt-0.5 shrink-0"
                      />
                      {batchWarning}
                    </div>
                  )}
                  <div className="flex items-center justify-between">
                    <p className="text-sm text-gray-600">
                      <span className="font-semibold text-gray-900">{batchSelected.length}</span> of{" "}
                      {batchDrafts.length} selected
                    </p>
                    <button
                      type="button"
                      onClick={() =>
                        setBatchSelected(
                          batchSelected.length === batchDrafts.length
                            ? []
                            : batchDrafts.map((_, i) => i),
                        )
                      }
                      disabled={batchSaving}
                      className="text-sm font-medium text-brand-700 hover:text-brand-900 disabled:opacity-50"
                    >
                      {batchSelected.length === batchDrafts.length ? "Deselect all" : "Select all"}
                    </button>
                  </div>

                  <div className="space-y-2">
                    {batchDrafts.map((draft, i) => {
                      const checked = batchSelected.includes(i);
                      const patientName = draft.patient_id
                        ? patients.find((p) => p.id === draft.patient_id)?.name
                        : null;
                      return (
                        <label
                          key={i}
                          className={`flex items-start gap-3 p-3 rounded-xl border cursor-pointer transition-all ${
                            checked
                              ? "border-brand-300 bg-brand-50/40"
                              : "border-gray-200 hover:bg-subtle"
                          }`}
                        >
                          <input
                            type="checkbox"
                            checked={checked}
                            disabled={batchSaving}
                            onChange={() =>
                              setBatchSelected((prev) =>
                                prev.includes(i) ? prev.filter((x) => x !== i) : [...prev, i],
                              )
                            }
                            className="mt-1 w-4 h-4 accent-brand-600"
                          />
                          <div className="min-w-0 flex-1">
                            <p className="font-semibold text-gray-900">{draft.title}</p>
                            <p className="text-sm text-gray-500 line-clamp-2 mt-0.5">
                              {draft.description}
                            </p>
                            <div className="flex items-center gap-2 flex-wrap mt-2">
                              <span
                                className={`px-2 py-0.5 rounded-full text-xs font-medium border ${getDifficultyColor(
                                  draft.difficulty,
                                )}`}
                              >
                                {draft.difficulty}
                              </span>
                              <span className="px-2 py-0.5 bg-gray-100 text-gray-700 text-xs font-medium rounded-full">
                                {draft.category}
                              </span>
                              {patientName && (
                                <span className="px-2 py-0.5 bg-teal-50 text-teal-700 text-xs font-medium rounded-full flex items-center gap-1">
                                  <FontAwesomeIcon icon={faHospitalUser} className="w-3 h-3" />
                                  {patientName}
                                </span>
                              )}
                              <span className="text-xs text-gray-400">
                                {draft.learning_objectives.length} objectives
                              </span>
                            </div>
                          </div>
                        </label>
                      );
                    })}
                  </div>
                </>
              )}
            </div>

            <div className="p-4 border-t border-hairline bg-subtle flex justify-end gap-3">
              <button
                type="button"
                onClick={closeBatchModal}
                disabled={batchGenerating || batchSaving}
                className="px-5 py-2.5 bg-surface border border-gray-200 hover:bg-gray-50 rounded-lg text-sm font-medium text-gray-700 transition-all disabled:opacity-50"
              >
                Cancel
              </button>
              {!batchDrafts ? (
                batchGenerating ? (
                  <button
                    type="button"
                    onClick={cancelBatch}
                    disabled={batchCancelling}
                    className="px-5 py-2.5 bg-surface border border-gray-300 text-gray-700 rounded-lg font-medium hover:bg-gray-50 transition-all disabled:opacity-50 flex items-center gap-2"
                  >
                    {batchCancelling ? (
                      <>
                        <FontAwesomeIcon icon={faSpinner} spin className="w-4 h-4" />
                        Stopping…
                      </>
                    ) : (
                      <>
                        <FontAwesomeIcon icon={faTimes} className="w-4 h-4" />
                        Stop
                      </>
                    )}
                  </button>
                ) : (
                  <button
                    type="button"
                    onClick={handleGenerateBatch}
                    className="px-5 py-2.5 bg-gradient-to-r from-brand-600 to-brand-800 text-white rounded-lg font-medium hover:from-brand-700 hover:to-brand-900 transition-all flex items-center gap-2 shadow-lg shadow-[0_4px_14px_-2px_rgb(27_107_123_/_0.45)]"
                  >
                    <FontAwesomeIcon icon={faLayerGroup} className="w-4 h-4" />
                    Generate {batchCount} Scenarios
                  </button>
                )
              ) : (
                <>
                  <button
                    type="button"
                    onClick={handleGenerateBatch}
                    disabled={batchSaving}
                    className="px-5 py-2.5 bg-surface border border-brand-300 text-brand-700 rounded-lg font-medium hover:bg-brand-50 transition-all disabled:opacity-50"
                  >
                    Regenerate
                  </button>
                  <button
                    type="button"
                    onClick={handleSaveBatch}
                    disabled={batchSaving || batchSelected.length === 0}
                    className="px-5 py-2.5 bg-brand-600 text-white rounded-lg font-medium hover:bg-brand-700 transition-all disabled:opacity-50 flex items-center gap-2 shadow-[0_2px_6px_rgba(27,107,123,0.2)]"
                  >
                    {batchSaving ? (
                      <>
                        <FontAwesomeIcon icon={faSpinner} spin className="w-4 h-4" />
                        Saving {batchSavedCount}/{batchSelected.length}…
                      </>
                    ) : (
                      `Save ${batchSelected.length} Scenario${batchSelected.length === 1 ? "" : "s"}`
                    )}
                  </button>
                </>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Details Modal */}
      {showDetailsModal && selectedScenario && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-surface rounded-xl w-full max-w-3xl max-h-[85vh] overflow-hidden flex flex-col shadow-[0_8px_30px_rgba(0,0,0,0.12)] border border-hairline">
            <div className="p-4 border-b border-hairline bg-subtle">
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-3 flex-wrap">
                    <div className="w-10 h-10 bg-brand-600/10 rounded-lg flex items-center justify-center">
                      <FontAwesomeIcon icon={faNotesMedical} className="text-brand-600 w-5 h-5" />
                    </div>
                    <h2 className="text-2xl font-bold text-gray-900">{selectedScenario.title}</h2>
                    {selectedScenario.is_ai_generated && (
                      <span className="px-2.5 py-1 bg-brand-100 text-brand-700 text-xs font-semibold rounded-full flex items-center gap-1">
                        <FontAwesomeIcon icon={faRobot} className="w-3 h-3" />
                        AI Generated
                      </span>
                    )}
                  </div>
                  <p className="text-gray-600">{selectedScenario.description}</p>
                </div>
                <button
                  onClick={() => setShowDetailsModal(false)}
                  className="p-2 hover:bg-gray-200 rounded-lg transition-colors"
                >
                  <FontAwesomeIcon icon={faTimes} className="w-5 h-5 text-gray-500" />
                </button>
              </div>
              <div className="flex items-center gap-3 mt-4 flex-wrap">
                <span
                  className={`px-3 py-1 rounded-full text-sm font-semibold border flex items-center gap-1 ${getDifficultyColor(
                    selectedScenario.difficulty,
                  )}`}
                >
                  <FontAwesomeIcon
                    icon={getDifficultyIcon(selectedScenario.difficulty)}
                    className="w-3 h-3"
                  />
                  {selectedScenario.difficulty}
                </span>
                <span className="px-3 py-1 bg-gray-100 text-gray-700 text-sm font-semibold rounded-full">
                  {selectedScenario.category}
                </span>
                <span className="text-sm text-gray-500 flex items-center gap-1">
                  <FontAwesomeIcon icon={faUsers} className="w-3.5 h-3.5" />
                  {selectedScenario.student_count} students
                </span>
                <span className="text-sm text-gray-400 flex items-center gap-1">
                  <FontAwesomeIcon icon={faCalendarDay} className="w-3.5 h-3.5" />
                  Created: {new Date(selectedScenario.created_at).toLocaleDateString()}
                </span>
              </div>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar">
              <div>
                <h3 className="text-lg font-bold text-gray-900 mb-3 flex items-center gap-2">
                  <FontAwesomeIcon icon={faStethoscope} className="text-brand-600" />
                  Patient Case
                </h3>
                <div className="bg-gray-50 rounded-xl p-5 border border-gray-200">
                  {selectedScenario.patient_case ? (
                    <div className="space-y-4">
                      {selectedScenario.patient_case.chief_complaint && (
                        <div className="bg-red-50 border border-red-200 rounded-xl p-4">
                          <p className="text-sm font-bold text-red-700 mb-1 flex items-center gap-2">
                            <FontAwesomeIcon icon={faExclamationTriangle} className="w-4 h-4" />
                            Chief Complaint
                          </p>
                          <p className="text-gray-800">
                            {selectedScenario.patient_case.chief_complaint}
                          </p>
                        </div>
                      )}
                      {selectedScenario.patient_case.vitals && (
                        <div>
                          <p className="text-sm font-bold text-gray-600 mb-2 flex items-center gap-2">
                            <FontAwesomeIcon icon={faHeartbeat} className="w-4 h-4 text-red-500" />
                            Vital Signs
                          </p>
                          <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
                            {Object.entries(selectedScenario.patient_case.vitals).map(
                              ([key, value]) => (
                                <div
                                  key={key}
                                  className="bg-surface rounded-lg p-3 border border-gray-200"
                                >
                                  <p className="text-xs text-gray-500 capitalize">
                                    {key.replace(/_/g, " ")}
                                  </p>
                                  <p className="font-semibold text-gray-800">{String(value)}</p>
                                </div>
                              ),
                            )}
                          </div>
                        </div>
                      )}
                      {selectedScenario.patient_case.medical_history && (
                        <div>
                          <p className="text-sm font-bold text-gray-600 mb-1">Medical History</p>
                          <p className="text-gray-800">
                            {selectedScenario.patient_case.medical_history}
                          </p>
                        </div>
                      )}
                      {selectedScenario.patient_case.physical_exam && (
                        <div>
                          <p className="text-sm font-bold text-gray-600 mb-1">
                            Physical Examination
                          </p>
                          <p className="text-gray-800">
                            {selectedScenario.patient_case.physical_exam}
                          </p>
                        </div>
                      )}
                      {selectedScenario.patient_case.diagnosis && (
                        <div>
                          <p className="text-sm font-bold text-gray-600 mb-1">Diagnosis</p>
                          <p className="text-gray-800">{selectedScenario.patient_case.diagnosis}</p>
                        </div>
                      )}
                      {selectedScenario.patient_case.treatment_plan && (
                        <div>
                          <p className="text-sm font-bold text-gray-600 mb-1">Treatment Plan</p>
                          <p className="text-gray-800">
                            {selectedScenario.patient_case.treatment_plan}
                          </p>
                        </div>
                      )}
                    </div>
                  ) : (
                    <p className="text-gray-500">No patient case details available</p>
                  )}
                </div>
              </div>

              <div>
                <h3 className="text-lg font-bold text-gray-900 mb-3 flex items-center gap-2">
                  <FontAwesomeIcon icon={faListCheck} className="text-brand-600" />
                  Learning Objectives
                </h3>
                <ul className="space-y-2">
                  {selectedScenario.learning_objectives &&
                  selectedScenario.learning_objectives.length > 0 ? (
                    selectedScenario.learning_objectives.map((objective, index) => (
                      <li key={index} className="flex items-start gap-3">
                        <div className="w-6 h-6 rounded-full bg-brand-600/10 flex items-center justify-center flex-shrink-0 mt-0.5">
                          <span className="text-sm font-bold text-brand-600">{index + 1}</span>
                        </div>
                        <p className="text-gray-700">{objective}</p>
                      </li>
                    ))
                  ) : (
                    <p className="text-gray-500">No learning objectives defined</p>
                  )}
                </ul>
              </div>
            </div>

            <div className="p-4 border-t border-hairline bg-subtle">
              <div className="flex justify-end gap-3">
                <button
                  onClick={() => setShowDetailsModal(false)}
                  className="px-5 py-2.5 bg-surface border border-gray-200 hover:bg-gray-50 rounded-lg text-sm font-medium text-gray-700 transition-all"
                >
                  Close
                </button>
                <button
                  onClick={() => {
                    setShowDetailsModal(false);
                    handleOpenAssignModal(selectedScenario);
                  }}
                  className="px-5 py-2.5 bg-brand-600 text-white rounded-lg font-medium hover:bg-brand-700 transition-all flex items-center gap-2 shadow-[0_2px_6px_rgba(27,107,123,0.2)]"
                >
                  <FontAwesomeIcon icon={faUserPlus} className="w-4 h-4" />
                  Assign to Students
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Assign Modal */}
      {showAssignModal && selectedScenario && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-surface rounded-xl w-full max-w-2xl max-h-[85vh] overflow-hidden flex flex-col shadow-[0_8px_30px_rgba(0,0,0,0.12)] border border-hairline">
            <div className="p-4 border-b border-hairline bg-subtle">
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-brand-600/10 rounded-lg flex items-center justify-center">
                    <FontAwesomeIcon icon={faUserPlus} className="text-brand-600 w-5 h-5" />
                  </div>
                  <div>
                    <h2 className="text-lg font-bold text-gray-900">Assign Scenario</h2>
                    <p className="text-sm text-gray-500">{selectedScenario.title}</p>
                  </div>
                </div>
                <button
                  onClick={() => setShowAssignModal(false)}
                  className="p-2 hover:bg-gray-200 rounded-lg transition-colors"
                >
                  <FontAwesomeIcon icon={faTimes} className="w-5 h-5 text-gray-500" />
                </button>
              </div>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar">
              <div className="bg-gray-50 rounded-xl p-4 border border-gray-200">
                <h3 className="text-sm font-bold text-gray-900 mb-3 flex items-center gap-2">
                  <FontAwesomeIcon icon={faCalendarDay} className="text-brand-600" />
                  Assignment Settings
                </h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className={labelClassName}>Deadline</label>
                    <div className="relative">
                      <FontAwesomeIcon
                        icon={faCalendarDay}
                        className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500"
                      />
                      <input
                        type="date"
                        value={assignDeadline}
                        onChange={(e) => setAssignDeadline(e.target.value)}
                        className={inputClassName + " pl-10"}
                      />
                    </div>
                  </div>
                  <div className="flex items-center pt-7">
                    <label className="flex items-center gap-3 cursor-pointer p-3 rounded-xl border border-gray-200 bg-surface hover:bg-gray-50 transition-colors w-full">
                      <input
                        type="checkbox"
                        checked={assignRequired}
                        onChange={(e) => setAssignRequired(e.target.checked)}
                        className="w-5 h-5 text-brand-600 rounded focus:ring-brand-600"
                      />
                      <span className="text-sm font-semibold text-gray-700">
                        Required for all students
                      </span>
                    </label>
                  </div>
                </div>
              </div>

              <div>
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-sm font-bold text-gray-900 flex items-center gap-2">
                    <FontAwesomeIcon icon={faUser} className="text-brand-600" />
                    Select Students
                  </h3>
                  <button
                    onClick={() => setSelectedStudents(filteredStudents.map((s) => s.id))}
                    className="text-sm text-brand-600 hover:text-brand-700 font-semibold"
                  >
                    Select All
                  </button>
                </div>
                <div className="mb-3">
                  <div className="relative">
                    <FontAwesomeIcon
                      icon={faSearch}
                      className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-500"
                    />
                    <input
                      type="text"
                      value={studentSearchQuery}
                      onChange={(e) => setStudentSearchQuery(e.target.value)}
                      placeholder="Search by name or email..."
                      className={inputClassName + " pl-10"}
                    />
                  </div>
                </div>
                <div className="border border-gray-200 rounded-xl max-h-[280px] overflow-y-auto custom-scrollbar">
                  {filteredStudents.length === 0 ? (
                    <div className="p-4 text-center text-gray-500 text-sm">
                      {studentSearchQuery
                        ? "No students match your search"
                        : "No students available"}
                    </div>
                  ) : (
                    <table className="w-full">
                      <thead className="bg-gray-50 sticky top-0">
                        <tr>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Select
                          </th>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Name
                          </th>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Email
                          </th>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Risk
                          </th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-100">
                        {filteredStudents.map((student) => (
                          <tr
                            key={student.id}
                            className={`transition-colors cursor-pointer ${
                              selectedStudents.includes(student.id)
                                ? "bg-brand-600/5 hover:bg-brand-600/10"
                                : "hover:bg-gray-50"
                            }`}
                            onClick={() => toggleStudentSelection(student.id)}
                          >
                            <td className="py-2.5 px-4" onClick={(e) => e.stopPropagation()}>
                              <input
                                type="checkbox"
                                checked={selectedStudents.includes(student.id)}
                                onChange={() => toggleStudentSelection(student.id)}
                                className="w-4 h-4 text-brand-600 rounded focus:ring-brand-600"
                              />
                            </td>
                            <td className="py-2.5 px-4 text-sm text-gray-800">
                              <div className="flex items-center gap-2">
                                <Avatar name={student.name} src={student.picture_url} size="xs" />
                                {student.name}
                              </div>
                            </td>
                            <td className="py-2.5 px-4 text-sm text-gray-500">{student.email}</td>
                            <td className="py-2.5 px-4">
                              <span
                                className={`px-2 py-0.5 text-xs font-bold rounded-full ${
                                  student.risk_level === "at_risk"
                                    ? "bg-red-100 text-red-700"
                                    : student.risk_level === "safe"
                                      ? "bg-emerald-100 text-emerald-700"
                                      : "bg-gray-100 text-gray-700"
                                }`}
                              >
                                {student.risk_level === "at_risk"
                                  ? "At risk"
                                  : student.risk_level === "safe"
                                    ? "On track"
                                    : "No prediction"}
                              </span>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </div>
                <p className="text-sm text-gray-500 mt-2">
                  {selectedStudents.length} student(s) selected
                </p>
              </div>
            </div>

            <div className="p-4 border-t border-hairline bg-subtle">
              <div className="flex justify-end gap-3">
                <button
                  onClick={() => setShowAssignModal(false)}
                  className="px-5 py-2.5 bg-surface border border-gray-200 hover:bg-gray-50 rounded-lg text-sm font-medium text-gray-700 transition-all"
                >
                  Cancel
                </button>
                <button
                  onClick={handleAssignScenario}
                  disabled={selectedStudents.length === 0 || !assignDeadline || assigning}
                  className="px-5 py-2.5 bg-brand-600 text-white rounded-lg font-medium hover:bg-brand-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 shadow-[0_2px_6px_rgba(27,107,123,0.2)]"
                >
                  {assigning && <FontAwesomeIcon icon={faSpinner} spin className="w-4 h-4" />}
                  Assign to {selectedStudents.length} Student
                  {selectedStudents.length !== 1 ? "s" : ""}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Link Patient Modal */}
      {showLinkPatientModal && linkPatientTarget && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-surface rounded-xl w-full max-w-lg max-h-[85vh] overflow-hidden flex flex-col shadow-[0_8px_30px_rgba(0,0,0,0.12)] border border-hairline">
            <div className="p-4 border-b border-hairline flex items-center justify-between bg-subtle">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-brand-600/10 rounded-lg flex items-center justify-center">
                  <FontAwesomeIcon icon={faHospitalUser} className="text-brand-600 w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-gray-900">Link Patient</h3>
                  <p className="text-sm text-gray-500 line-clamp-1">{linkPatientTarget.title}</p>
                </div>
              </div>
              <button
                onClick={closeLinkPatientModal}
                className="p-2 hover:bg-gray-200 rounded-lg transition-colors"
              >
                <FontAwesomeIcon icon={faTimes} className="w-5 h-5 text-gray-500" />
              </button>
            </div>

            <div className="p-4 space-y-3 overflow-y-auto flex-1">
              <p className="text-sm text-gray-500">
                Students only see patients linked to their assigned scenarios — pick one so it
                shows up for anyone already assigned this scenario.
              </p>

              <button
                type="button"
                onClick={() => setLinkPatientId("")}
                className={`w-full flex items-center justify-between p-3 rounded-xl border-2 transition-all ${
                  linkPatientId === ""
                    ? "border-brand-600 bg-brand-600/5"
                    : "border-gray-200 hover:border-gray-300 hover:bg-gray-50"
                }`}
              >
                <span className="text-sm font-medium text-gray-700">No linked patient</span>
                {linkPatientId === "" && (
                  <div className="w-6 h-6 bg-brand-600 rounded-full flex items-center justify-center">
                    <FontAwesomeIcon icon={faCheck} className="w-3.5 h-3.5 text-white" />
                  </div>
                )}
              </button>

              {linkPatientSelected && (
                <div className="p-3 bg-teal-50 border border-teal-200 rounded-xl flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 bg-teal-100 rounded-full flex items-center justify-center text-teal-700">
                      <FontAwesomeIcon icon={faHospitalUser} className="w-4 h-4" />
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-gray-800">
                        {linkPatientSelected.name}
                      </p>
                      <p className="text-xs text-gray-500">
                        {linkPatientSelected.diagnosis} · {linkPatientSelected.mimic_id}
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={() => setLinkPatientId("")}
                    className="text-xs text-teal-700 hover:text-teal-900 font-medium"
                  >
                    Clear
                  </button>
                </div>
              )}

              <div className="border border-gray-200 rounded-xl overflow-hidden">
                <div className="p-3 border-b border-gray-200 bg-subtle">
                  <div className="relative">
                    <FontAwesomeIcon
                      icon={faSearch}
                      className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500"
                    />
                    <input
                      type="text"
                      value={linkPatientSearchQuery}
                      onChange={(e) => setLinkPatientSearchQuery(e.target.value)}
                      placeholder="Search patients by name, diagnosis, MIMIC ID, or room..."
                      className={inputClassName + " pl-10"}
                    />
                  </div>
                </div>
                <div className="max-h-[260px] overflow-y-auto custom-scrollbar">
                  {loadingPatients ? (
                    <div className="p-8 text-center">
                      <FontAwesomeIcon icon={faSpinner} spin className="w-6 h-6 text-brand-600" />
                      <p className="text-sm text-gray-500 mt-2">Loading patients...</p>
                    </div>
                  ) : linkModalFilteredPatients.length === 0 ? (
                    <div className="p-6 text-center text-gray-500 text-sm">
                      {linkPatientSearchQuery
                        ? "No patients match your search."
                        : "No MIMIC-IV patients available."}
                    </div>
                  ) : (
                    <table className="w-full">
                      <thead className="bg-gray-50 sticky top-0">
                        <tr>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Patient
                          </th>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Diagnosis
                          </th>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            Room
                          </th>
                          <th className="text-left py-2.5 px-4 text-xs font-semibold text-gray-600">
                            MIMIC ID
                          </th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-100">
                        {linkModalFilteredPatients.map((patient) => (
                          <tr
                            key={patient.id}
                            onClick={() => setLinkPatientId(patient.id)}
                            className={`cursor-pointer transition-colors ${
                              linkPatientId === patient.id
                                ? "bg-brand-600/5 hover:bg-brand-600/10"
                                : "hover:bg-gray-50"
                            }`}
                          >
                            <td className="py-2.5 px-4">
                              <div className="flex items-center gap-2">
                                <div className="w-7 h-7 bg-brand-600/10 rounded-full flex items-center justify-center text-brand-600 text-xs font-semibold">
                                  {patient.name.charAt(0)}
                                </div>
                                <div>
                                  <p className="text-sm font-medium text-gray-800">
                                    {patient.name}
                                  </p>
                                  <p className="text-xs text-gray-500">
                                    {patient.age}yo {patient.gender}
                                  </p>
                                </div>
                              </div>
                            </td>
                            <td className="py-2.5 px-4 text-sm text-gray-600">
                              {patient.diagnosis}
                            </td>
                            <td className="py-2.5 px-4 text-sm text-gray-600">
                              {patient.room_number}
                            </td>
                            <td className="py-2.5 px-4">
                              <span className="text-xs font-mono text-gray-500">
                                {patient.mimic_id}
                              </span>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </div>
              </div>
            </div>

            <div className="p-4 border-t border-hairline bg-subtle flex justify-end gap-3">
              <button
                onClick={closeLinkPatientModal}
                className="px-5 py-2.5 bg-surface border border-gray-200 hover:bg-gray-50 rounded-lg text-sm font-medium text-gray-700 transition-all"
              >
                Cancel
              </button>
              <button
                onClick={handleSavePatientLink}
                disabled={savingPatientLink}
                className="px-5 py-2.5 bg-brand-600 text-white rounded-lg font-medium hover:bg-brand-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 shadow-[0_2px_6px_rgba(27,107,123,0.2)]"
              >
                {savingPatientLink && <FontAwesomeIcon icon={faSpinner} spin className="w-4 h-4" />}
                Save
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
