import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from '@react-pdf/renderer';

// Server-side PDF generation for the automated competency report
// (manuscript F6, Objective 2.4). Rendered on demand by
// /api/faculty/reports/competency/[studentId].

export interface CompetencyReportData {
  student: { name: string; email: string };
  campus: string;
  generatedBy: string;
  generatedAt: string;
  competencies: { name: string; latest: number; count: number }[];
  quiz: { attempts: number; avgScore: number | null; bestScore: number | null };
  recentAttempts: { title: string; score: number | null; submittedAt: string }[];
  vitals: { readings: number; anomalies: number };
  ehr: { tpr: number; ivf: number; notes: number; reviewedNotes: number };
}

const TEAL = '#1B6B7B';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica', color: '#1f2937' },
  header: { borderBottomWidth: 2, borderBottomColor: TEAL, paddingBottom: 10, marginBottom: 16 },
  brand: { fontSize: 18, fontFamily: 'Helvetica-Bold', color: TEAL },
  subtitle: { fontSize: 9, color: '#6b7280', marginTop: 2 },
  sectionTitle: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: TEAL,
    marginTop: 14,
    marginBottom: 6,
  },
  metaRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 2 },
  metaLabel: { color: '#6b7280' },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingVertical: 4,
    alignItems: 'center',
  },
  headRow: { backgroundColor: '#f3f4f6', fontFamily: 'Helvetica-Bold' },
  cellWide: { flex: 3, paddingHorizontal: 4 },
  cell: { flex: 1, paddingHorizontal: 4, textAlign: 'right' },
  barTrack: { flex: 2, height: 6, backgroundColor: '#e5e7eb', borderRadius: 3, marginHorizontal: 4 },
  statGrid: { flexDirection: 'row', gap: 8 },
  statBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 4,
    padding: 8,
    alignItems: 'center',
  },
  statValue: { fontSize: 14, fontFamily: 'Helvetica-Bold', color: TEAL },
  statLabel: { fontSize: 8, color: '#6b7280', marginTop: 2, textAlign: 'center' },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#9ca3af',
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 6,
  },
});

function scoreColor(score: number): string {
  if (score >= 80) return '#059669';
  if (score >= 60) return '#d97706';
  return '#dc2626';
}

function CompetencyReport({ data }: { data: CompetencyReportData }) {
  return (
    <Document title={`Competency Report - ${data.student.name}`}>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>iCARE++ Student Competency Report</Text>
          <Text style={styles.subtitle}>{data.campus} · College of Health Sciences</Text>
        </View>

        <View style={styles.metaRow}>
          <Text>
            <Text style={styles.metaLabel}>Student: </Text>
            <Text style={{ fontFamily: 'Helvetica-Bold' }}>{data.student.name}</Text>
            {'  '}({data.student.email})
          </Text>
        </View>
        <View style={styles.metaRow}>
          <Text>
            <Text style={styles.metaLabel}>Generated: </Text>
            {data.generatedAt}
          </Text>
          <Text>
            <Text style={styles.metaLabel}>Generated by: </Text>
            {data.generatedBy}
          </Text>
        </View>

        <Text style={styles.sectionTitle}>Validated Competency Scores</Text>
        {data.competencies.length === 0 ? (
          <Text style={{ color: '#6b7280' }}>No validated competency scores recorded yet.</Text>
        ) : (
          <View>
            <View style={[styles.row, styles.headRow]}>
              <Text style={styles.cellWide}>Competency Area</Text>
              <View style={styles.barTrack} />
              <Text style={styles.cell}>Latest</Text>
              <Text style={styles.cell}>Ratings</Text>
            </View>
            {data.competencies.map((competency) => (
              <View key={competency.name} style={styles.row}>
                <Text style={styles.cellWide}>{competency.name}</Text>
                <View style={styles.barTrack}>
                  <View
                    style={{
                      width: `${Math.min(competency.latest, 100)}%`,
                      height: 6,
                      backgroundColor: scoreColor(competency.latest),
                      borderRadius: 3,
                    }}
                  />
                </View>
                <Text style={[styles.cell, { color: scoreColor(competency.latest) }]}>
                  {competency.latest}%
                </Text>
                <Text style={styles.cell}>{competency.count}</Text>
              </View>
            ))}
          </View>
        )}

        <Text style={styles.sectionTitle}>Assessment Performance</Text>
        <View style={styles.statGrid}>
          <View style={styles.statBox}>
            <Text style={styles.statValue}>{data.quiz.attempts}</Text>
            <Text style={styles.statLabel}>Submitted Attempts</Text>
          </View>
          <View style={styles.statBox}>
            <Text style={styles.statValue}>
              {data.quiz.avgScore !== null ? `${data.quiz.avgScore}%` : '—'}
            </Text>
            <Text style={styles.statLabel}>Average Score</Text>
          </View>
          <View style={styles.statBox}>
            <Text style={styles.statValue}>
              {data.quiz.bestScore !== null ? `${data.quiz.bestScore}%` : '—'}
            </Text>
            <Text style={styles.statLabel}>Best Score</Text>
          </View>
        </View>

        {data.recentAttempts.length > 0 && (
          <View>
            <Text style={styles.sectionTitle}>Recent Quiz Attempts</Text>
            <View style={[styles.row, styles.headRow]}>
              <Text style={styles.cellWide}>Assessment</Text>
              <Text style={styles.cell}>Score</Text>
              <Text style={[styles.cell, { flex: 2 }]}>Submitted</Text>
            </View>
            {data.recentAttempts.map((attempt, i) => (
              <View key={i} style={styles.row}>
                <Text style={styles.cellWide}>{attempt.title}</Text>
                <Text
                  style={[
                    styles.cell,
                    { color: attempt.score !== null ? scoreColor(attempt.score) : '#6b7280' },
                  ]}
                >
                  {attempt.score !== null ? `${attempt.score}%` : '—'}
                </Text>
                <Text style={[styles.cell, { flex: 2 }]}>{attempt.submittedAt}</Text>
              </View>
            ))}
          </View>
        )}

        <Text style={styles.sectionTitle}>Clinical Training Activity</Text>
        <View style={styles.statGrid}>
          <View style={styles.statBox}>
            <Text style={styles.statValue}>{data.vitals.readings}</Text>
            <Text style={styles.statLabel}>Vital Sign Readings</Text>
          </View>
          <View style={styles.statBox}>
            <Text style={[styles.statValue, { color: '#dc2626' }]}>{data.vitals.anomalies}</Text>
            <Text style={styles.statLabel}>Flagged Anomalies</Text>
          </View>
          <View style={styles.statBox}>
            <Text style={styles.statValue}>{data.ehr.tpr}</Text>
            <Text style={styles.statLabel}>TPR Entries</Text>
          </View>
          <View style={styles.statBox}>
            <Text style={styles.statValue}>{data.ehr.ivf}</Text>
            <Text style={styles.statLabel}>IVF Records</Text>
          </View>
          <View style={styles.statBox}>
            <Text style={styles.statValue}>
              {data.ehr.reviewedNotes}/{data.ehr.notes}
            </Text>
            <Text style={styles.statLabel}>Notes Reviewed</Text>
          </View>
        </View>

        <Text style={styles.footer} fixed>
          iCARE++ — ML-Driven Clinical Competency Assessment and Adaptive Learning System ·
          Batangas State University TNEU ARASOF-Nasugbu · Confidential academic record (RA 10173)
        </Text>
      </Page>
    </Document>
  );
}

export async function renderCompetencyReport(data: CompetencyReportData): Promise<Buffer> {
  return renderToBuffer(<CompetencyReport data={data} />);
}
