import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
  type DocumentProps,
} from '@react-pdf/renderer';
import type { ReactElement, ReactNode } from 'react';

/** What renderToBuffer accepts: a <Document> root, not any element. */
export type ReportDocument = ReactElement<DocumentProps>;

export const TEAL = '#1B6B7B';

/**
 * Shared look for every generated report. Kept in one place so a new report
 * type inherits the letterhead, table and stat styling rather than restating it.
 */
export const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica', color: '#1f2937' },
  header: { borderBottomWidth: 2, borderBottomColor: TEAL, paddingBottom: 10, marginBottom: 16 },
  brand: { fontSize: 18, fontFamily: 'Helvetica-Bold', color: TEAL },
  subtitle: { fontSize: 9, color: '#6b7280', marginTop: 2 },
  sectionTitle: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: TEAL,
    marginTop: 14,
    marginBottom: 6,
  },
  metaRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 2 },
  metaLabel: { color: '#6b7280' },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingVertical: 4,
    alignItems: 'center',
  },
  headRow: { backgroundColor: '#f3f4f6', fontFamily: 'Helvetica-Bold' },
  cellWide: { flex: 3, paddingHorizontal: 4 },
  cell: { flex: 1, paddingHorizontal: 4, textAlign: 'right' },
  barTrack: { flex: 2, height: 6, backgroundColor: '#e5e7eb', borderRadius: 3, marginHorizontal: 4 },
  statGrid: { flexDirection: 'row', gap: 8 },
  statBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 4,
    padding: 8,
    alignItems: 'center',
  },
  statValue: { fontSize: 14, fontFamily: 'Helvetica-Bold', color: TEAL },
  statLabel: { fontSize: 8, color: '#6b7280', marginTop: 2, textAlign: 'center' },
  empty: { color: '#9ca3af', fontSize: 9, paddingVertical: 6 },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#9ca3af',
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 6,
  },
});

export function scoreColor(score: number): string {
  if (score >= 80) return '#059669';
  if (score >= 60) return '#d97706';
  return '#dc2626';
}

export interface ReportMeta {
  campus: string;
  generatedBy: string;
  generatedAt: string;
}

/** Letterhead, meta block and footer shared by every report type. */
export function ReportShell({
  title,
  heading,
  meta,
  metaRows,
  children,
}: {
  title: string;
  heading: string;
  meta: ReportMeta;
  metaRows: { label: string; value: string }[];
  children: ReactNode;
}) {
  return (
    <Document title={title}>
      <Page size="A4" style={styles.page} wrap>
        <View style={styles.header}>
          <Text style={styles.brand}>{heading}</Text>
          <Text style={styles.subtitle}>{meta.campus} · College of Health Sciences</Text>
        </View>

        <View>
          {metaRows.map((row) => (
            <View key={row.label} style={styles.metaRow}>
              <Text style={styles.metaLabel}>{row.label}</Text>
              <Text>{row.value}</Text>
            </View>
          ))}
          <View style={styles.metaRow}>
            <Text style={styles.metaLabel}>Generated by</Text>
            <Text>{meta.generatedBy}</Text>
          </View>
          <View style={styles.metaRow}>
            <Text style={styles.metaLabel}>Generated at</Text>
            <Text>{meta.generatedAt}</Text>
          </View>
        </View>

        {children}

        <Text style={styles.footer} fixed>
          iCARE++ · Generated live from current records · Confidential academic record
        </Text>
      </Page>
    </Document>
  );
}

export function StatGrid({ items }: { items: { label: string; value: string | number }[] }) {
  return (
    <View style={styles.statGrid}>
      {items.map((item) => (
        <View key={item.label} style={styles.statBox}>
          <Text style={styles.statValue}>{String(item.value)}</Text>
          <Text style={styles.statLabel}>{item.label}</Text>
        </View>
      ))}
    </View>
  );
}

/**
 * Simple table. The first column is wide, the rest are right-aligned numerics —
 * which is the shape every report here needs.
 */
export function Table({
  head,
  rows,
  emptyText = 'No records yet.',
}: {
  head: string[];
  rows: (string | number)[][];
  emptyText?: string;
}) {
  if (rows.length === 0) {
    return <Text style={styles.empty}>{emptyText}</Text>;
  }
  return (
    <View>
      <View style={[styles.row, styles.headRow]}>
        {head.map((label, i) => (
          <Text key={label} style={i === 0 ? styles.cellWide : styles.cell}>
            {label}
          </Text>
        ))}
      </View>
      {rows.map((row, r) => (
        <View key={r} style={styles.row} wrap={false}>
          {row.map((cell, i) => (
            <Text key={i} style={i === 0 ? styles.cellWide : styles.cell}>
              {String(cell)}
            </Text>
          ))}
        </View>
      ))}
    </View>
  );
}

export async function renderReport(element: ReportDocument): Promise<Buffer> {
  return await renderToBuffer(element);
}
